Refactor: L1 update
iotaledger/wasp-legacy pull request #1012
Opened 2022-05-16 16:11 UTC by jorgemmsilva

updates to support all the new versions of iotago/hornet & inx plugins

many breaking changes were made in iotago addressed in this PR, multiple fixes related to the way storage deposit is calculated.

2022-05-16 17:18 UTC, lmoe approved these changes
Amazing work!

2022-05-16 17:18 UTC, lmoe commented on contracts/wasm/testcore/src/testcore.rs
> +    let transfer = wasmlib::ScTransfer::iotas(1000000);
Should we add the `iscp.Mi` const to the wasmlib?

2022-05-16 18:26 UTC, dessaya approved these changes

2022-05-16 18:26 UTC, dessaya commented on go.mod
> +require (
Why two require blocks? :thinking:

2022-05-16 18:28 UTC, BugFreeSoftware requested changes

2022-05-16 18:28 UTC, BugFreeSoftware commented on contracts/wasm/testwasmlib/go/testwasmlib/testwasmlib.go
> +var (
This won't work in Wasm environment. We don't want Wasp/iotago dependencies. They can introduce horrible dependency chains, include stuff that isn't supported by TinyGo, include stuff that isn't deterministic, and we don't have the corresponding code for Rust and Typescript, so those versions of the SCs will now fail when I test them.
Please revert the lines in testwasmlib.go and testwasmlib_test.go that were changed to use TestNFTID and TestTokenID.

2022-05-16 18:29 UTC, BugFreeSoftware commented on contracts/wasm/testcore/src/testcore.rs
> +    let transfer = wasmlib::ScTransfer::iotas(1000000);
Will look into that after the merge. There is a design decision around dust in the Wasm code that I need to revisit after these changes to make them consistent again.

2022-05-17 10:03 UTC, jorgemmsilva commented on go.mod
> +require (
new go things :sparkles: 

https://stackoverflow.com/a/69433550/6749639

2022-05-17 10:08 UTC, jorgemmsilva commented on contracts/wasm/testwasmlib/go/testwasmlib/testwasmlib.go
> +var (
sure things, will remove the iscp import. :+1: 
On another note, I'm thinking it would be nice if we could trim it down and import the `iscp` package in tinygo. It should be quite minimalistic and only export simple types.

2022-05-17 10:49 UTC, merged