Gascalibration
iotaledger/wasp-legacy pull request #1127
Opened 2022-07-07 00:50 UTC by ivange94

# Description of change

Gas calibration tests

Please write a summary of your changes and why you made them. 

## Links to any relevant issues

Be sure to reference any related issues by adding `fixes issue #`.

## Type of change

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the [contribution guidelines](https://wiki.iota.org/smart-contracts/contribute) for this project
- [x] I have performed a self-review of my own code
- [x] I have selected the `develop` branch as the target branch
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

2022-07-14 14:32 UTC, dessaya approved these changes

2022-07-14 14:32 UTC, dessaya commented on contracts/wasm/gascalibration/executiontime/Cargo.toml
> +authors = ["John Doe <john@doe.org>"]
maybe put your name here? Or just IOTA Foundation? Same in other `Cargo.toml` files

2022-07-18 10:26 UTC, jorgemmsilva approved these changes
too many`nolint` state that don't explain why they are needed, and should disable only the specific rule that is needed.

the "execution time" benchmark doesn't make much sense, the wasm languages are basically flat :disappointed:

2022-07-18 10:26 UTC, jorgemmsilva commented on packages/vm/viewcontext/viewcontext.go
> +	l1Params       *parameters.L1Params // nolint
question: why is nolint needed here?

btw, we should not ignore ALL the linting rules, only the rules that shouldn't apply to the code in question, example: `//nolint:deadcode`

2022-07-18 12:20 UTC, ivange94 commented on packages/vm/viewcontext/viewcontext.go
> +	l1Params       *parameters.L1Params // nolint
I didn't just ignore all. I added nolint here and one other place because I wasn't sure how to handle them. The linter reported that these fields are not used. For one of them the field was actually being used. It's the `Chain.lastReceipt`. Not sure why the linter was saying its not used. For the one you commented on, I did a search in my editor and couldn't find a reference to the field but still wasn't sure if the right move was to delete it so I ignored.

2022-07-18 13:05 UTC, jorgemmsilva commented on packages/vm/viewcontext/viewcontext.go
> +	l1Params       *parameters.L1Params // nolint
very rarely the liter is mistaken :stuck_out_tongue:  anyway, you should never "abolish all rules", in this case it would be something like `//nolint:unused`.

However, these variables should be *removed* if not in use.

2022-07-18 13:06 UTC, jorgemmsilva requested changes
please remove the unused variables, instead of marking them as "lint ignore".

2022-07-18 13:08 UTC, ivange94 commented on packages/vm/viewcontext/viewcontext.go
> +	l1Params       *parameters.L1Params // nolint
In this particular case the linter isn't wrong. But it also complains about `Chain.lastReceipt` but that field is been used and deleting it causes compiler errors

2022-07-18 14:23 UTC, ivange94 commented on packages/vm/viewcontext/viewcontext.go
> +	l1Params       *parameters.L1Params // nolint
Strange. I couldn't find any reference to `Chain.lastReceipt` this time. I could swear the build was breaking before when I deleted it 😂

2022-07-19 09:24 UTC, jorgemmsilva approved these changes

2022-07-19 09:24 UTC, jorgemmsilva commented on contracts/wasm/gascalibration/executiontime/test/executiontime_test.go
> +	. "github.com/iotaledger/wasp/contracts/wasm/gascalibration"
is this needed?

2022-07-19 12:06 UTC, ivange94 commented on contracts/wasm/gascalibration/executiontime/test/executiontime_test.go
> +	. "github.com/iotaledger/wasp/contracts/wasm/gascalibration"
Fixed

2022-07-19 12:07 UTC, merged