Docs - Develop - Core Concepts - Core Contracts
iotaledger/wasp-legacy pull request #1236
Opened 2022-08-18 16:04 UTC by lucas-tortora

# Description of change

A few small edits to the Core Concepts > Core Contract.  Mostly around using consistent formatting. 

## Type of change

- Documentation enhancement

## How the change has been tested

Wiki was built locally

## Change checklist

- [x] I have followed the [contribution guidelines](https://wiki.iota.org/smart-contracts/contribute) for this project
- [x] I have selected the `develop` branch as the target branch
- [x] I have made corresponding changes to the documentation

2022-08-18 16:34 UTC, dessaya approved these changes

2022-08-22 14:27 UTC, lucas-tortora commented
@iotaledger/tech-writers , whenever you have a minute, could you please take a look at this?

2022-08-23 12:48 UTC, aleksei-korolev requested changes

2022-08-23 12:48 UTC, aleksei-korolev commented on documentation/docs/guide/core_concepts/core_contracts/accounts.md
> +A map of [`TokenID`](#tokenid) => `big.Int`. An empty Token ID represents the L1 base tokens (a key with length 0).
```suggestion
A map of [`TokenID`](#tokenid) => `big.Int`. An empty token ID (a string of zero length) represents the L1 base token.
```

2022-08-23 12:48 UTC, aleksei-korolev commented on documentation/docs/guide/core_concepts/core_contracts/accounts.md
> +A map of [`TokenID`](#tokenid) => `big.Int`. An empty Token ID represents the L1 base tokens (a key with length 0).
```suggestion
A map of [`TokenID`](#tokenid) => `big.Int`. An empty token ID (a string of zero length) represents the L1 base token.
```

2022-08-23 12:48 UTC, aleksei-korolev commented on documentation/docs/guide/core_concepts/core_contracts/blob.md
> +Blobs can be used to store arbitrary data. For example, the collection of Wasm binaries needed to deploy a smart contract.
```suggestion
Blobs can be used to store arbitrary data like, for example, a collection of Wasm binaries needed to deploy a smart contract.
```

Is it possible to be more specific? What exactly uses these binaries and what exactly for? For example, "...utility binaries that are referenced by all smart contracts"

2022-08-23 12:48 UTC, aleksei-korolev commented on documentation/docs/guide/core_concepts/core_contracts/blocklog.md
> +- Previous L1 commitment (except for block index 0.)
```suggestion
- Previous L1 commitment (except for block index 0).
```

One is not like the others.

2022-08-23 12:48 UTC, aleksei-korolev commented on documentation/docs/guide/core_concepts/core_contracts/errors.md
> +- The error code ([`ErrorCode`](#errorcode)) .
```suggestion
- The error code ([`ErrorCode`](#errorcode)).
```

2022-08-23 12:48 UTC, aleksei-korolev commented on documentation/docs/guide/core_concepts/core_contracts/evm.md
> +- `evmw` (optional [`GasRatio`](#gasratio) - default: `1:1`): The ISC : EVM gas ratio.
```suggestion
- `evmw` (optional [`GasRatio`](#gasratio) - default: `1:1`): The ISC to EVM gas ratio.
```

2022-08-23 15:36 UTC, lucas-tortora commented on documentation/docs/guide/core_concepts/core_contracts/blob.md
> +Blobs can be used to store arbitrary data. For example, the collection of Wasm binaries needed to deploy a smart contract.
I'm afraid I don't have the answer to your question

2022-08-26 08:08 UTC, aleksei-korolev approved these changes

2022-09-02 11:51 UTC, merged