Docs - Develop - Core Concepts - Chains and Nodes
iotaledger/wasp-legacy pull request #1242
Opened 2022-08-22 18:49 UTC by lucas-tortora

# Description of change

A few small edits to the Solo.  Mostly around formatting. 

## Type of change

- Documentation enhancement

## How the change has been tested

Wiki was built locally

## Change checklist

- [x] I have followed the [contribution guidelines](https://wiki.iota.org/smart-contracts/contribute) for this project
- [x] I have selected the `develop` branch as the target branch
- [x] I have made corresponding changes to the documentation

2022-08-22 18:50 UTC, lucas-tortora commented
@iotaledger/tech-writers could you takea look at this whenever you get a chance?

2022-08-23 13:30 UTC, aleksei-korolev requested changes

2022-08-23 13:30 UTC, aleksei-korolev commented on documentation/docs/guide/chains_and_nodes/docker_standalone.md
> +2. Switch to the `develop` branch and build the main image:
```suggestion
2. Switch to the `develop` branch:
```

2022-08-23 13:30 UTC, aleksei-korolev commented on documentation/docs/guide/chains_and_nodes/installing-wasp.md
> +It's recommended to use [WSL](https://docs.microsoft.com/en-us/windows/wsl/install) on Windows and follow
```suggestion
On Windows, we recommend you to use [WSL](https://docs.microsoft.com/en-us/windows/wsl/install) and follow
```

2022-08-23 13:30 UTC, aleksei-korolev commented on documentation/docs/guide/chains_and_nodes/node-config.md
> +Both authentication methods allow any request and have 'root' permissions.
```suggestion
Both authentication methods have 'root' permissions and would allow any request.
```

2022-08-23 13:30 UTC, aleksei-korolev commented on documentation/docs/guide/chains_and_nodes/publisher.md
> +IRI. In the future, Wasp will possibly support [ZMQ](https://zeromq.org/) and [MQTT](https://mqtt.org/) publishers too.
Should we even mention a future possibility?

2022-08-23 13:30 UTC, aleksei-korolev commented on documentation/docs/guide/chains_and_nodes/testnet.md
> +:::caution unscheduled network resets
I think you've been Header Capitilizing it in other PRs, should we choose one and add it to the style guide?

2022-08-23 13:30 UTC, aleksei-korolev commented on documentation/docs/guide/chains_and_nodes/testnet.md
> +You can access the testnet via a series of endpoints that have been made available.
```suggestion
You can access the testnet via the following endpoints:
```

2022-08-23 16:18 UTC, lucas-tortora commented on documentation/docs/guide/chains_and_nodes/testnet.md
> +:::caution unscheduled network resets
I've added a few where appropriate, as the default labels are a bit generic.  We can certainly add it if you're in favour as well.

2022-08-24 14:44 UTC, lucas-tortora commented on documentation/docs/guide/chains_and_nodes/publisher.md
> +IRI. In the future, Wasp will possibly support [ZMQ](https://zeromq.org/) and [MQTT](https://mqtt.org/) publishers too.
as long as we can deliver, I think so :)

2022-08-25 09:09 UTC, aleksei-korolev approved these changes
All good, just one small formatting error.

2022-08-25 09:09 UTC, aleksei-korolev commented on documentation/docs/guide/chains_and_nodes/docker_standalone.md
> +"faucetAddress": "http://hornet:8091"
I don't think you've meant this change
```suggestion
  "apiAddress": "http://hornet:14265",
  "faucetAddress": "http://hornet:8091"
```

2022-09-02 11:52 UTC, lmoe approved these changes

2022-09-02 11:52 UTC, merged