Docs - Develop - EVM
iotaledger/wasp-legacy pull request #1245
Opened 2022-08-23 16:14 UTC by lucas-tortora

# Description of change

A few small edits to the EVM section

## Type of change

- Documentation enhancement

## How the change has been tested

Wiki was built locally

## Change checklist

- [x] I have followed the [contribution guidelines](https://wiki.iota.org/smart-contracts/contribute) for this project
- [x] I have selected the `develop` branch as the target branch
- [x] I have made corresponding changes to the documentation

## Todo
- [ ] Get links for the prerequisites in the ERC721 example
- [ ] Add prerequisites to the other examples

2022-08-23 16:15 UTC, lucas-tortora commented
@iotaledger/tech-writers could you please take a look at this whenever you have a moment?

2022-08-25 09:53 UTC, aleksei-korolev requested changes

2022-08-25 09:53 UTC, aleksei-korolev commented on documentation/docs/guide/evm/compatibility.md
> +etc.) and to provide a way to execute EVM code to manipulate the state.
```suggestion
provides EVM support in IOTA Smart Contracts. It stores the EVM state (account balances, state, code,
etc.) and provides a way to execute EVM code to manipulate the state.
```

2022-08-25 09:53 UTC, aleksei-korolev commented on documentation/docs/guide/evm/compatibility.md
> +like [MetaMask](https://metamask.io/), which assume that the EVM code will be run on an Ethereum blockchain composed of
```suggestion
like [MetaMask](https://metamask.io/), which assume that the EVM code runs on an Ethereum blockchain composed of
```

2022-08-25 09:53 UTC, aleksei-korolev commented on documentation/docs/guide/evm/compatibility.md
> +Ethereum blocks containing Ethereum transactions. Unfortunately, since ISC works in a fundamentally different way,
```suggestion
Ethereum blocks containing Ethereum transactions. Since ISC works in a fundamentally different way,
```

2022-08-25 09:53 UTC, aleksei-korolev commented on documentation/docs/guide/evm/compatibility.md
> +The Wasp node provides a JSON-RPC service, the standard protocol used by Ethereum tools. Upon receiving a signed
A bullet is missing. Would it make sense to introduce a header and turn bullet points into normal paragraphs?

2022-08-25 09:53 UTC, aleksei-korolev commented on documentation/docs/guide/evm/examples/ERC721.md
> +decentralized network.
> including a real-world asset on a decentralized network.

While it is technically true, I think it complicates the article without contributing to it. Can we just cut that part and mention what is the ERC721 standard instead?

2022-08-25 09:53 UTC, aleksei-korolev commented on documentation/docs/guide/evm/examples/ERC721.md
>  ## Prerequisites
There are supposed to be some links, right? Are these articles not written yet?

2022-08-25 09:53 UTC, aleksei-korolev commented on documentation/docs/guide/evm/examples/ERC721.md
>  ## About ERC721
I think this should go either to the very beginning or (better) to a separate article.

2022-08-25 09:53 UTC, aleksei-korolev commented on documentation/docs/guide/evm/using.md
>  * `--evm-gas-limit <n>`: Block gas limit (default: 15000000).
```suggestion
* `--evm-gas-limit <n>`: Block gas limit (15000000 gas units by default).
```

2022-08-25 09:53 UTC, aleksei-korolev commented on documentation/docs/guide/evm/using.md
> +* `--evm-gas-ratio <a>:<b>`: ISC gas : EVM gas ratio (default 1:1). You can change the gas ratio after deployment by
```suggestion
* `--evm-gas-ratio <a>:<b>`: ISC gas : EVM gas ratio (1:1 by default). You can change the gas ratio after deployment by
```

2022-08-25 12:34 UTC, lucas-tortora commented on documentation/docs/guide/evm/examples/ERC721.md
>  ## Prerequisites
They are supposed to, I think. Well, either that or they'll be gone. I need to check in with the author.  It's one of the `Todo`s in the PR description

2022-08-25 12:36 UTC, lucas-tortora commented on documentation/docs/guide/evm/compatibility.md
> +The Wasp node provides a JSON-RPC service, the standard protocol used by Ethereum tools. Upon receiving a signed
It did for some, but along the way it lost form and seemed really forced.  I think perhaps we could turn it into a table or something in the future.

2022-08-25 13:39 UTC, lucas-tortora commented on documentation/docs/guide/evm/examples/ERC721.md
>  ## About ERC721
I've reformatted the prerequisites section a bit.  I think that should always be at the top, so the user knows what they need before diving into things.

2022-08-25 13:40 UTC, lucas-tortora commented
@anistark , whenever you have a minute please take a look a this.  Particularley the prerequisites in the ERC how tos

2022-09-13 11:36 UTC, lucas-tortora commented
@dessaya  could you, or someone you see fit, please review this?

2022-09-13 11:47 UTC, dessaya approved these changes
LGTM, but maybe @fijter can take another look

2022-09-13 11:48 UTC, lucas-tortora commented
> LGTM, but maybe @fijter can take another look

thanks!

2022-09-14 12:41 UTC, lucas-tortora commented
@aleksei-korolev do you require any further changes for this this PR or can I get your approval?

2022-09-14 12:45 UTC, anistark approved these changes

2022-09-14 12:45 UTC, anistark commented
> @anistark , whenever you have a minute please take a look a this. Particularley the prerequisites in the ERC how tos

Completely missed this. Went through it now. LGTM.

2022-09-14 15:44 UTC, aleksei-korolev approved these changes

2022-10-03 11:18 UTC, jorgemmsilva commented
lets merge this?
please resolve the conflicts :pray:

2022-10-03 13:43 UTC, lucas-tortora commented
> lets merge this? please resolve the conflicts pray

I think that should be better now :)

2022-10-03 14:05 UTC, merged