Ipfs
iotaledger/wasp-legacy pull request #130
Opened 2021-03-12 06:13 UTC by Juliusan

i've implemented a downloader, which supports downloading from http, https and from a configurable ipfs http gateway.

2021-03-12 07:15 UTC, lunfardo314 commented on packages/downloader/downloader.go
> +	this.downloadsMutex.Unlock()
more idiomatic pattern is:
``` go
mutex.Lock()
defer mutex.Unlock()

// the rest
```

2021-03-12 07:15 UTC, lunfardo314 commented on packages/downloader/downloader.go
> +func (this *Downloader) markStarted(uri string) {
see above

2021-03-12 07:15 UTC, lunfardo314 commented on packages/downloader/downloader.go
> +	this.downloadsMutex.Lock()
see above

2021-03-12 07:15 UTC, lunfardo314 commented on packages/downloader/downloader_test.go
> +var FILE []byte = []byte{'s', 'o', 'm', 'e', ' ', 'f', 'i', 'l', 'e', ' ', 'f', 'o', 'r', ' ', 't', 'e', 's', 't', 'i', 'n', 'g'} // should be constant, but...
?

2021-03-12 08:34 UTC, Juliusan commented on packages/downloader/downloader_test.go
> +var FILE []byte = []byte{'s', 'o', 'm', 'e', ' ', 'f', 'i', 'l', 'e', ' ', 'f', 'o', 'r', ' ', 't', 'e', 's', 't', 'i', 'n', 'g'} // should be constant, but...
Just some constants for tests. I don't know what's unclear here :-) The comment is, because I wasn't able to define byte array typed slice constant. I had to use `var` instead of `const`. See https://stackoverflow.com/questions/13137463/declare-a-constant-array.

2021-03-12 14:23 UTC, dessaya requested changes
Good PR!

Don't be intimidated by the amount of comments; it's mostly just me being pedantic about idiomatic Go. None of my observations are really critical, except maybe the one about the race condition.

2021-03-12 14:23 UTC, dessaya commented on packages/downloader/downloader.go
> +	downloadsMutex *sync.Mutex
No need to make it a pointer, it can be just `sync.Mutex`; its zero value is already a properly initialized instance.

2021-03-12 14:23 UTC, dessaya commented on packages/downloader/downloader.go
> +func (this *Downloader) DownloadAndStore(hash hashing.HashValue, uri string, cache coretypes.BlobCache) error {
`this` is not idiomatic Go. Suggest renaming to `d`.

https://github.com/golang/go/wiki/CodeReviewComments#receiver-names

2021-03-12 14:23 UTC, dessaya commented on packages/downloader/downloader.go
> +	downloads      map[string]bool // Just a HashSet. The value of the element is not important. The existence of key in the map is what counts.
The comment could be just a GoDoc compliant sentence:

```
// downloads is the set of urls currently being downloaded
downloads map[string]bool
```

https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences

2021-03-12 14:23 UTC, dessaya commented on packages/downloader/downloader.go
> +//          e.g. ipfs://QmeyMc1i9KLqqyqYCksDZiwntxwuiz5Z1hbLBrHvAXyjMZ
This maybe should also be in GoDoc format.

2021-03-12 14:23 UTC, dessaya commented on packages/downloader/downloader.go
> +	} else {
No need for `else`: https://github.com/golang/go/wiki/CodeReviewComments#indent-error-flow

2021-03-12 14:23 UTC, dessaya commented on packages/downloader/downloader.go
> +		this.markStarted(uri)
I think there is a race condition: another thread could have started the download between checking `this.contains()` and here.

Options to fix this:
* Add a `loadOrStore()` method that does both things while keeping the mutex lock.
* Replace the map+mutex with a [sync.Map](https://golang.org/pkg/sync/#Map) and use its `LoadOrStore` method.
* Replace the map+mutex+multiple goroutines with a channel and a single goroutine with a main loop.

2021-03-12 14:23 UTC, dessaya commented on packages/downloader/downloader.go
> +		go func() {
This function is maybe too long, can some part of it be extracted into smaller functions?

2021-03-12 14:23 UTC, dessaya commented on packages/downloader/downloader.go
> +			}
For example this block may be a `download(uri string) ([]byte, error)` function

2021-03-12 14:23 UTC, dessaya commented on packages/downloader/downloader.go
> +	var ok bool
You can replace

```
var ok bool
_, ok = this.downloads[uri]
```

with

```
_, ok := this.downloads[uri]
```

2021-03-12 14:23 UTC, dessaya commented on packages/downloader/downloader.go
> +	response, err = http.Get(url)
Same here: 

```
response, err := http.Get(url)
```

2021-03-12 14:23 UTC, dessaya commented on packages/downloader/downloader_test.go
> +const FILE_CID string = "someunrealistichash12345"
ALL_CAPS is not idiomatic, even for constants. Use `mockServerPort`, `fileCID`, etc.

https://github.com/golang/go/wiki/CodeReviewComments#mixed-caps

2021-03-12 14:23 UTC, dessaya commented on packages/downloader/downloader_test.go
> +var FILE []byte = []byte{'s', 'o', 'm', 'e', ' ', 'f', 'i', 'l', 'e', ' ', 'f', 'o', 'r', ' ', 't', 'e', 's', 't', 'i', 'n', 'g'} // should be constant, but...
```
var file = []byte("some file for testing")
```

Also, no need for the comment

2021-03-12 14:23 UTC, dessaya commented on packages/downloader/downloader_test.go
> +		cid = c.Param("cid")
cid := c.Param("cid")

2021-03-12 14:23 UTC, dessaya commented on packages/downloader/downloader_test.go
> +		var err error = e.Start(MOCK_SERVER_PORT)
`err := e.Start(MOCK_SERVER_PORT)`

2021-03-12 14:23 UTC, dessaya commented on packages/downloader/downloader_test.go
> +	e = echo.New()
`e := echo.New()`

2021-03-12 14:23 UTC, dessaya commented on packages/downloader/downloader_test.go
> +	ctx, cancel = context.WithTimeout(context.Background(), 5*time.Second)
```
ctx, cancel := ...
err := ...
```

2021-03-12 14:23 UTC, dessaya commented on packages/downloader/downloader_test.go
> +	var err error
Same thing, replace with `:=` :)

2021-03-12 14:23 UTC, dessaya commented on packages/downloader/downloader_test.go
> +	stopMockServer(server)
Use defer for this:

```
server := startMockServer()
defer stopMockServer()
```

2021-03-12 14:23 UTC, dessaya commented on packages/downloader/downloader_test.go
> +	time.Sleep(100 * time.Millisecond) // Time to wait for download completion
Suggest replacing `time.Sleep` with events, so that the test can finish instantly.

Also, the other `time.Sleep` above should be possible to remove by starting echo with a custom listener, as discussed.

(This can be done in another PR later).

2021-03-12 14:23 UTC, dessaya commented on plugins/downloader/plugin.go
> +// PluginName is the name of the web API plugin.
~web API~ downloader

2021-03-12 14:23 UTC, dessaya commented on plugins/downloader/plugin.go
> +	}
```
configure := ...
run := ...
log := ...
```

2021-03-15 08:48 UTC, Juliusan commented on packages/downloader/downloader.go
> +//          e.g. ipfs://QmeyMc1i9KLqqyqYCksDZiwntxwuiz5Z1hbLBrHvAXyjMZ
I hope, I understood well, what a godoc format is.

2021-03-15 08:53 UTC, Juliusan commented on packages/downloader/downloader.go
> +		go func() {
I don't see advantage in turning a one time used block into separate function.

2021-03-15 08:53 UTC, Juliusan commented on packages/downloader/downloader.go
> +			}
Ok, I can do that.

2021-03-15 09:02 UTC, Juliusan commented on packages/downloader/downloader.go
> +	var ok bool
Is it necessary? I like seeing declared types of the variables... :-(

2021-03-15 10:00 UTC, Juliusan commented on packages/downloader/downloader_test.go
> +const FILE_CID string = "someunrealistichash12345"
I used `constMockServerPort`, `constFileCID` for that. So, it can be seen that these names represent constants.

2021-03-15 10:08 UTC, Juliusan commented on packages/downloader/downloader_test.go
> +	time.Sleep(100 * time.Millisecond) // Time to wait for download completion
To replace this `timer.Sleep` with events, I'll have to include some mechanism in application code, which will really be used for tests only. Is this a normal practice in Go - program mechanisms for testing right into production code?

2021-03-15 11:33 UTC, Juliusan commented on packages/downloader/downloader.go
> +		this.markStarted(uri)
I've implemented the first option.

2021-03-15 12:59 UTC, Juliusan commented on packages/downloader/downloader_test.go
> +	time.Sleep(100 * time.Millisecond) // Time to wait for download completion
I've removed this sleep from the test. I'll look into another sleep later.

2021-03-15 15:48 UTC, dessaya approved these changes

2021-03-16 11:41 UTC, Juliusan commented on packages/downloader/downloader_test.go
> +	time.Sleep(100 * time.Millisecond) // Time to wait for download completion
I've removed the second sleep as well.

2021-03-16 11:46 UTC, merged