Refactored inccounter
iotaledger/wasp-legacy pull request #133
Opened 2021-03-24 13:42 UTC by melatron

2021-03-24 13:47 UTC, lunfardo314 requested changes

2021-03-24 13:47 UTC, lunfardo314 commented on contracts/native/inccounter/impl.go
> +	ctx.Contract().String()
?

2021-03-24 13:47 UTC, lunfardo314 commented on contracts/native/inccounter/impl.go
>  		ctx.Log().Debugf("PostRequestToSelfWithDelay. remaining repeats = %d", numRepeats-1)
the message must be changed accordingly

2021-03-24 13:47 UTC, lunfardo314 commented on contracts/native/inccounter/inccounter_test.go
> +		WithTransfer(ledgerstate.ColorIOTA, 1)
WithIotas(1)

2021-03-25 14:23 UTC, BugFreeSoftware commented
Most of these changes were already merged as part of my refactoring of the entire contracts folder

2021-03-25 16:02 UTC, closed without merging