Gpa - State manager
iotaledger/wasp-legacy pull request #1375
Opened 2022-10-17 18:10 UTC by Juliusan

TODO... # Description of change

Please write a summary of your changes and why you made them. 

## Links to any relevant issues

Be sure to reference any related issues by adding `fixes issue #`.

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the [contribution guidelines](https://wiki.iota.org/smart-contracts/contribute) for this project
- [ ] I have performed a self-review of my own code
- [ ] I have selected the `develop` branch as the target branch
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2022-11-07 13:46 UTC, kape1395 requested changes

2022-11-07 13:46 UTC, kape1395 commented on packages/chain/statemanager/smMessages/gpa_message.go
> +type GpaMessage struct {
Replace with gpa.BasicMessage

2022-11-07 13:46 UTC, kape1395 commented on packages/chain/statemanager/state_manager.go
> +	//	smT.updatePublicKeys(accessNodePubKeys)
Cleanup?

2022-11-07 13:46 UTC, kape1395 commented on packages/chain/statemanager/state_manager.go
> +package statemanager
Don't we have any test for this?

2022-11-07 13:46 UTC, kape1395 commented on packages/chain/statemanager/state_manager.go
> +	stateManagerGPA, err := smGPA.New(chainID, nr, walFolder, store, smLog)
Don't we need the AckHandler here?

2022-11-07 13:46 UTC, kape1395 commented on packages/chain/statemanager/smInputs/chain_receive_confirmed_alias_output.go
> +package smInputs
I would move all the input/message object to the smGPA package with interfaces introduced.

2022-11-07 13:46 UTC, kape1395 commented on packages/chain/statemanager/smInputs/consensus_decided_state.go
> +			StateBaseline:      coreutil.NewChainStateSync().SetSolidIndex(virtualStateAccess.BlockIndex()).GetSolidIndexBaseline(), // TODO - move it to Respond method parameters?
This logic looks hidden here. Would move it from here to make messages and inputs without much logic.

2022-11-07 13:46 UTC, kape1395 commented on packages/chain/statemanager/smInputs/chain_block_produced.go
> +func (cbpT *ChainBlockProduced) Respond(err error) {
Not sure, that's good approach to mess with channels here.

2022-11-07 13:46 UTC, kape1395 commented on packages/chain/statemanager/smMessages/block_message.go
> +	return NewBlockMessage(block, "UNKNOWN"), nil
That `UNKNOWN` looks strange.

2022-11-07 13:46 UTC, kape1395 commented on packages/chain/statemanager/smMessages/get_block_message.go
> +func NewGetBlockMessageFromBytes(data []byte) (*GetBlockMessage, error) {
Here we introduce 4th way to approach serialization.

2022-11-07 13:46 UTC, kape1395 commented on packages/chain/statemanager/smUtils/block_cache.go
> +type blockCache struct {
Don't sound like an util. Maybe move it to the smGPA package or its sub-package?

2022-11-07 13:46 UTC, kape1395 commented on packages/chain/statemanager/smUtils/time_provider.go
> +//
Cleanup?

2022-11-07 13:46 UTC, kape1395 commented on packages/chain/statemanager/smUtils/time_provider.go
> +func NewArtifficialTimeProvider(nowOpt ...time.Time) TimeProvider {
Maybe move it to a test file or package?
Now it is not very clear, why a single variable set/get object is useful.

2022-11-07 13:46 UTC, kape1395 commented on packages/chain/statemanager/smUtils/block_cache_timers.go
> +type BlockCacheTimers struct {
Unused?

2022-11-07 13:46 UTC, kape1395 commented on packages/chain/statemanager/smUtils/block_wal.go
> +type blockWAL struct {
Does this replace the `packages/wal`?

2022-11-07 13:46 UTC, kape1395 commented on packages/chain/statemanager/smUtils/block_wal.go
> +	block, err := state.BlockFromBytes(blockBytes)
Maybe we have to check the hash on read?

2022-11-07 13:46 UTC, kape1395 commented on packages/chain/statemanager/smUtils/block_wal_empty.go
> +type emptyBlockWAL struct{}
Do we actually need that?

2022-11-07 13:46 UTC, kape1395 commented on packages/chain/statemanager/smUtils/block_wal_mocked.go
> +type mockedBlockWAL struct {
Move the test utilities to the `packages/testutil/...`?

2022-11-07 13:46 UTC, kape1395 commented on packages/chain/statemanager/smUtils/block_wal_rapid_test.go
> +		takeFrom = rapid.IntRange(0, 1).Example()
You should use Draw() instead of Example().

2022-11-07 13:46 UTC, kape1395 commented on packages/chain/statemanager/smUtils/test_utils.go
> +// Copyright 2020 IOTA Stiftung
Move to the testutil/... ?

2022-11-07 13:46 UTC, kape1395 commented on packages/chain/statemanager/smGPA/state_manager_gpa.go
> +	if len(timersOpt) > 0 {
Is it worth introducing those default? Makes things less explicit, harder to track the real values in use.

2022-11-07 13:46 UTC, kape1395 commented on packages/chain/statemanager/smGPA/state_manager_gpa.go
> +	if walFolder == "" {
This condition should probably be hidden in the WAL part?

2022-11-07 13:46 UTC, kape1395 commented on packages/chain/statemanager/smGPA/state_manager_gpa.go
> +		smT.log.Warnf("Unknown input received, ignoring it: type=%T, message=%v", input, input)
Should panic on bad inputs, because that's controlled by the current node.

2022-11-07 13:46 UTC, kape1395 commented on packages/chain/statemanager/smGPA/state_manager_gpa.go
> +	return ""
Should provide info on what's the current problem the SM works on.
Can be logged periodically from the SM thread.

2022-11-07 13:46 UTC, kape1395 commented on packages/chain/statemanager/smGPA/state_manager_gpa.go
> +		return smMessages.NewBlockMessageFromBytes(data)
Why not to use the Unmarshal... directly?
Asked me to add the Unmarshaler interface to the message, now don't use that.

2022-11-07 13:46 UTC, kape1395 commented on packages/chain/statemanager/smGPA/state_manager_gpa.go
> +		return gpa.NoMessages()
return `nil` if there is no messages to send.

2022-11-07 13:46 UTC, kape1395 commented on packages/chain/statemanager/smGPA/block_request_state.go
> +type stateBlockRequestImplementation interface { // Abstract methods of struct stateBlockRequest
I don't get what is this for? Maybe implementation is bad term here?

2022-11-07 13:46 UTC, kape1395 commented on packages/chain/statemanager/smGPA/state_manager_gpa_test.go
> +	nodeIDs := smUtils.MakeNodeIDs([]int{0, 1, 2, 3, 4, 5, 6, 7, 8, 9})
gpa package had a function for this already.

2022-11-07 13:46 UTC, kape1395 commented on packages/chain/statemanager/smGPA/block_request_cds.go
> +type consensusDecidedStateBlockRequest struct {
Why the request context is not considered here?

2022-11-07 13:46 UTC, kape1395 commented on packages/chain/statemanager/smGPA/block_request_state.go
> +type stateBlockRequestImplementation interface { // Abstract methods of struct stateBlockRequest
Maybe that's (response) receiver or (request) sender?

Can't we use simple struct for all of this with a callback parameter?

2022-11-08 08:33 UTC, Juliusan commented on packages/chain/statemanager/state_manager.go
> +package statemanager
Not yet. Working on that.

2022-11-08 08:37 UTC, Juliusan commented on packages/chain/statemanager/state_manager.go
> +	stateManagerGPA, err := smGPA.New(chainID, nr, walFolder, store, smLog)
Not necessary. Requesting for blocks is repeated by algorithm. There is no necessity to ensure every message delivery.

2022-11-08 08:39 UTC, Juliusan commented on packages/chain/statemanager/smGPA/state_manager_gpa.go
> +		return smMessages.NewBlockMessageFromBytes(data)
This was done prior to `Unmarshal` was introduced. Using `Unmarshal` would require creating new object prior to that. It could be done in constructor or it could be done here. I can change this, if needed.

2022-11-08 08:39 UTC, Juliusan commented on packages/chain/statemanager/smGPA/state_manager_gpa.go
> +		return gpa.NoMessages()
`gpa.NoMessages()` means exactly that. Or doesn't it? And it is more explicit.

2022-11-08 11:09 UTC, kape1395 commented on packages/chain/statemanager/smGPA/state_manager_gpa.go
> +		return gpa.NoMessages()
Yes. But that is non-idiomatic.

2022-11-08 15:07 UTC, Juliusan commented on packages/chain/statemanager/smGPA/block_request_cds.go
> +type consensusDecidedStateBlockRequest struct {
It is done here: https://github.com/Juliusan/wasp/blob/8f43be4c940b64fb55a13584fce212a25848af0f/packages/chain/statemanager/smGPA/block_request_cds.go#L34-L36

2022-11-09 08:13 UTC, kape1395 approved these changes

2022-11-09 08:15 UTC, merged