Evm artifacts
iotaledger/wasp-legacy pull request #1522
Opened 2022-12-07 22:41 UTC by ivange94

# Description of change

Remove evm artifacts from the repository.

2022-12-07 22:45 UTC, jorgemmsilva approved these changes

2022-12-07 22:45 UTC, jorgemmsilva commented on .github/workflows/build-test.yml
> +        run: npm install -g solc
maybe just this will suffice and we don't need npm
```
sudo apt-get install solc
```

2022-12-08 14:22 UTC, dessaya approved these changes

2022-12-08 14:26 UTC, muXxer requested changes
`//go:embed` fails if we do this.
so the linter can't run properly. can we somehow tell the linter to compile the files before running?

Maybe we need to add the compile step to the lint action in `build-test.yml` as well?

2022-12-08 22:02 UTC, muXxer approved these changes

2022-12-09 00:15 UTC, merged