ServerNodes = Inverse(AccessNodes)
iotaledger/wasp-legacy pull request #1617
Opened 2023-01-04 08:28 UTC by kape1395

A chain has to use ServerNodes to query requests of blocks instead of AccessNodes.
The ServerNodes is the inverse of AccessNodes, considering the latter as a relation.
Now the access nodes get connected to the chain automatically.

2023-01-04 15:36 UTC, muXxer requested changes

2023-01-04 15:36 UTC, muXxer commented on packages/webapi/testutil/mockchain.go
> +// ConfigUpdated implements chain.Chain
```suggestion
// ServersUpdated implements chain.Chain
```

2023-01-04 15:36 UTC, muXxer commented on packages/solo/chain.go
> +// ConfigUpdated implements chain.Chain
```suggestion
// ServersUpdated implements chain.Chain
```

2023-01-04 15:36 UTC, muXxer commented on packages/peering/lpp/lppNetImpl.go
> +// TrustedPeers implements the peering.TrustedNetworkManager interface.
```suggestion
// TrustedPeersListener implements the peering.TrustedNetworkManager interface.
```

2023-01-04 15:36 UTC, muXxer commented on packages/chains/accessMgr/amDist/msg.go
> +		return nil, fmt.Errorf("accessMgrImpl::UnmarshalMessage: data to short")
```suggestion
		return nil, fmt.Errorf("accessMgrImpl::UnmarshalMessage: data too short")
```

2023-01-04 15:36 UTC, muXxer commented on packages/chains/accessMgr/amDist/msg.go
> +	return nil, fmt.Errorf("accessMgrImpl::UnmarshalMessage: cannot parse message starting with: %v", logData)
IMO its better to encode the logData to hex.

2023-01-04 15:36 UTC, muXxer commented on packages/gpa/ack_handler.go
> +	delete(a.counters, peerID)
We should use the generic `ShrinkingMap` from hive.go for all long living maps that get modified over time, otherwise this will leak memory.

2023-01-04 15:36 UTC, muXxer commented on packages/chains/accessMgr/accessMgr_test.go
> +				continue
I don't get that logic of these two for loops.
Should this line continue the outer for loop instead? If so, you need to label it.

2023-01-04 15:36 UTC, muXxer commented on packages/chains/accessMgr/accessMgr_test.go
> +				continue
How does this test even fail? After a certain timeout?

2023-01-04 15:36 UTC, muXxer commented on packages/chains/accessMgr/accessMgr.go
> +	reqChainAccessNodes pipe.Pipe
why not also call these variables `Pipe` like `reqTrustedNodesPipe` ?

2023-01-04 15:36 UTC, muXxer commented on packages/chains/accessMgr/accessMgr.go
> +	msgTypeAccessMgr byte = iota
why is `iota` used here if it is only 1 constant anyway? I would set it directly to the specific number instead.

2023-01-04 15:36 UTC, muXxer commented on packages/chains/accessMgr/accessMgr.go
> +	netPeeringID := peering.PeeringIDFromBytes([]byte("AccessMgr"))
Is this correct here? Should that be the same value for all nodes?

BTW: I saw that we sometimes hash the chainID plus some additional bytes, and sometimes not.
Maybe this is also wrong? See `mempool.go` and `node.go`.

2023-01-04 15:36 UTC, muXxer commented on packages/chains/accessMgr/accessMgr.go
> +	ami.dismissPeerBuf = append(ami.dismissPeerBuf, peerPubKey)
Is `dismissPeerBuf` threadsafe? Shouldn't we at least add some mutex?

2023-01-04 15:36 UTC, muXxer commented on packages/chains/accessMgr/accessMgr.go
> +	nodeID := gpa.NodeID(pubKey.String())
Why do we use a string for the `NodeID` type btw? Why don't we use the `PublicKeyKey` type instead? :)
That should use less memory and should be faster to compare, in map lookups etc.

2023-01-04 15:36 UTC, muXxer commented on packages/chains/accessMgr/accessMgr.go
> +	nodeID := gpa.NodeID(pubKey.String())
![grafik](https://user-images.githubusercontent.com/32371094/210577536-89ebe019-0d61-4931-9a3f-662ad397d19b.png)

2023-01-04 15:36 UTC, muXxer commented on packages/chains/accessMgr/amDist/accessMgrDist.go
> +	serversUpdatedCB func(isc.ChainID, []*cryptolib.PublicKey) // Called when a set fo servers has changed for a chain.
```suggestion
	serversUpdatedCB func(isc.ChainID, []*cryptolib.PublicKey) // Called when a set of servers has changed for a chain.
```

2023-01-04 15:36 UTC, muXxer commented on packages/chains/accessMgr/amDist/accessMgrDist.go
> +	chain, ok := amd.chains[input.chainID]
Can't all these functions be executed in parallel by different threads?
If so, the amd.chains access needs to be locked with mutexes.

2023-01-04 15:36 UTC, muXxer commented on packages/chains/accessMgr/amDist/accessMgrDist.go
> +	sendDone := true &&
```
	sendDone := true &&
```
the true is not needed.

2023-01-04 15:36 UTC, muXxer commented on packages/chains/accessMgr/amDist/accessMgrDist.go
> +			newMsgAccess(msg.Sender(), amn.ourLC, amn.peerLC, amn.accessFor.AsSlice(), amn.serverFor.AsSlice()),
is this also no problem that we access all these slices without mutexes?

2023-01-09 10:23 UTC, kape1395 reviewed
Responses to comments.

2023-01-09 10:23 UTC, kape1395 commented on packages/chains/accessMgr/accessMgr.go
> +	reqChainAccessNodes pipe.Pipe
Thanks for pointing this out. Will fix.

2023-01-09 10:23 UTC, kape1395 commented on packages/chains/accessMgr/accessMgr.go
> +	msgTypeAccessMgr byte = iota
All the distributed / GPA algorithms are now designed in the same way. I kept the constant assignment like this to have the implementation uniform with other algorithms. I don't know if setting it to 0 would make less of a surprise in the future.

2023-01-09 10:23 UTC, kape1395 commented on packages/chains/accessMgr/accessMgr.go
> +	netPeeringID := peering.PeeringIDFromBytes([]byte("AccessMgr"))
Yes. We have 1 AccessMgr per Wasp node. It manages access for all the chains. Thus the identifier is a constant. Mempools are per chain, chain nodes - as well. And the CmtLog instances are per chain/committee, etc. That's why the identifiers are constructed in different ways.

2023-01-09 10:23 UTC, kape1395 commented on packages/chains/accessMgr/accessMgr.go
> +	ami.dismissPeerBuf = append(ami.dismissPeerBuf, peerPubKey)
This attribute is only accessed from a single thread, i.e., from the run() function. I was trying to control the goroutines with the GPA approach, primarily by running a component on a dedicated routine. Other components then communicate with the component's routine via channels and pipes. The code is organized this way to avoid using mutexes too much.

2023-01-09 10:23 UTC, kape1395 commented on packages/chains/accessMgr/accessMgr.go
> +	nodeID := gpa.NodeID(pubKey.String())
The initial reason was to handle a hierarchy of algorithms. I.e. consensus uses RBC, ACS, and others. The idea was to have different node identifiers for each protocol in the hierarchy. Later the hierarchy was resolved differently.
Also, I wanted to keep the GPA framework independent of other parts in the wasp code base. So that's less of an argument.
Now a lot of tests are using string-based node ids. Mainly to have them short, which is useful when analyzing logs.

2023-01-09 10:23 UTC, kape1395 commented on packages/chains/accessMgr/accessMgr_test.go
> +				continue
The intention was to have a failure on a timeout. That's because the tested function works asynchronously; thus, there is no clear way in the test to determine when the result is reached. I do that here by repeatedly checking the conditions with delays until the condition passes or a timeout occurs.

The loop is strange. Rewrote it.

2023-01-09 10:23 UTC, kape1395 commented on packages/chains/accessMgr/amDist/accessMgrDist.go
> +	chain, ok := amd.chains[input.chainID]
No, this object is always used from a single thread. That's designed intentionally to avoid complicating the code by mixing the distributed algorithms with threading.

2023-01-09 10:23 UTC, kape1395 commented on packages/chains/accessMgr/amDist/accessMgrDist.go
> +	sendDone := true &&
It is here only to have the conditions below aligned and more readable. I hope that `true &&` would be optimized out by the compiler anyway.

2023-01-09 10:23 UTC, kape1395 commented on packages/chains/accessMgr/amDist/accessMgrDist.go
> +			newMsgAccess(msg.Sender(), amn.ourLC, amn.peerLC, amn.accessFor.AsSlice(), amn.serverFor.AsSlice()),
No, not a problem, as mentioned above --  the object is accessed from a single thread.

2023-01-09 10:23 UTC, kape1395 commented on packages/chains/accessMgr/amDist/msg.go
> +		return nil, fmt.Errorf("accessMgrImpl::UnmarshalMessage: data to short")
Thanks, updated is all the similar places.

2023-01-09 10:23 UTC, kape1395 commented on packages/gpa/ack_handler.go
> +	delete(a.counters, peerID)
Probably yes. But maybe we should do that in a separate PR and for all the uses of maps? There will be a lot of them. Also, it seems like more functions would be needed for the `ShrinkingMap` to keep the code readable, e.g. `MustGet`.

2023-01-09 16:48 UTC, muXxer commented on packages/gpa/ack_handler.go
> +	delete(a.counters, peerID)
I created an issue #1627

2023-01-09 16:50 UTC, muXxer commented on packages/chains/accessMgr/accessMgr_test.go
> +				continue
But still, shouldn't have have a defined timeout? Like a context with Timeout with 1 minute.
Otherwise it will run as long as the timeout parameter for the tests is set (I put there 1h because we have so many tests).

2023-01-09 16:52 UTC, muXxer commented on packages/chains/accessMgr/accessMgr.go
> +	msgTypeAccessMgr byte = iota
Can you add a new `const` section if you use the `iota` keyword?

```

const (
	msgTypeAccessMgr byte = iota
)

const (
	resendPeriod          = 3 * time.Second
	distDebugTick         = 10 * time.Second
	distTimeTick          = 1 * time.Second
)
```

2023-01-09 16:53 UTC, muXxer commented on packages/chains/accessMgr/accessMgr.go
> +	netPeeringID := peering.PeeringIDFromBytes([]byte("AccessMgr"))
I created another PR #1626 to fix what I mean.

2023-01-09 16:54 UTC, muXxer commented on packages/chains/accessMgr/accessMgr.go
> +	ami.dismissPeerBuf = append(ami.dismissPeerBuf, peerPubKey)
ok perfect.

2023-01-09 17:01 UTC, muXxer commented on packages/chains/accessMgr/accessMgr.go
> +	nodeID := gpa.NodeID(pubKey.String())
Ok but still wouldn't it be better to have `type NodeID [32]byte` then?
So we don't have the string comparisons everywhere.

2023-01-09 17:59 UTC, muXxer commented on packages/chains/accessMgr/accessMgr.go
> +	nodeID := gpa.NodeID(pubKey.String())
I added a PR #1630 to do these changes.

2023-01-09 18:12 UTC, muXxer commented on packages/chains/accessMgr/accessMgr_test.go
> +				continue
I created a PR #1631 to address that.

2023-01-09 18:12 UTC, muXxer commented on packages/chains/accessMgr/accessMgr.go
> +	msgTypeAccessMgr byte = iota
I created a PR #1631 to address that.

2023-01-10 08:56 UTC, muXxer approved these changes

2023-01-10 08:59 UTC, merged