Fix: optimize receive req endpoint
iotaledger/wasp-legacy pull request #1643
Opened 2023-01-10 18:01 UTC by jorgemmsilva

https://github.com/iotaledger/wasp/issues/1638

![Selection_002](https://user-images.githubusercontent.com/1187222/211627460-6805e272-f2dd-4b32-bcf3-d7a54ae263da.png)

2023-01-10 18:36 UTC, dessaya approved these changes

2023-01-10 18:58 UTC, muXxer approved these changes

2023-01-10 18:58 UTC, muXxer commented on packages/webapi/v1/request/request.go
>  		o.requestsCache.Set(reqID, true)
```suggestion
```

2023-01-10 19:51 UTC, muXxer requested changes
in `EnqueueOffLedgerRequest` in `offledger.go` there is a `c.requestCache.Set(reqID, true)` missing in line 61.

line 64 can be removed as well.

2023-01-11 07:53 UTC, kape1395 commented on packages/webapi/v1/request/request.go
>  		o.requestsCache.Set(reqID, true)
Please wait for me with this.

2023-01-11 08:20 UTC, kape1395 requested changes
Let's use the latest state from the chain.

2023-01-11 11:59 UTC, kape1395 approved these changes
Several minor comments.

2023-01-11 11:59 UTC, kape1395 commented on packages/vm/core/blocklog/external.go
> +	return IsRequestProcessedInternal(partition, requestID)
Doesn't it sound suspicious to have the "*Internal" function public?

2023-01-11 11:59 UTC, kape1395 commented on packages/webapi/v1/endpoints.go
> -		chainutil.GetAccountBalance,
Maybe we should leave these endpoints in the API even if we don't use them internally?

2023-01-11 12:00 UTC, jorgemmsilva commented on packages/webapi/v1/endpoints.go
> -		chainutil.GetAccountBalance,
those are not endpoints :joy: 

the function name is misleading. those were just utility functions that were used before, not anymore.

2023-01-11 12:08 UTC, jorgemmsilva commented on packages/vm/core/blocklog/external.go
> +	return IsRequestProcessedInternal(partition, requestID)
you're right, addressing that :+1:

2023-01-11 12:36 UTC, dessaya approved these changes

2023-01-11 12:36 UTC, dessaya commented on packages/chain/chain.go
> +	LatestState    StateFreshness = iota // ActiveState, if exist; Confirmed state otherwise.
Maybe rename to something like `StateFreshnessAuto` or `Default`? Because this looks repetitive and not very clear:

```
Chain.LatestState(chain.LatestState)
```

2023-01-11 12:50 UTC, kape1395 commented on packages/chain/chain.go
> +	LatestState    StateFreshness = iota // ActiveState, if exist; Confirmed state otherwise.
Renamed it to ActiveOrCommittedState.

2023-01-11 16:02 UTC, muXxer commented on packages/webapi/v1/endpoints.go
> -		chainutil.GetAccountBalance,
got confused the same way yesterday hahaha :D

2023-01-11 16:40 UTC, muXxer commented on packages/chain/node.go
> +		return latestConfirmedState, nil
Why don't we call the store here like we do in `ActiveOrCommittedState` ?

2023-01-11 16:40 UTC, muXxer commented on packages/webapi/v2/services/vm.go
> +	"github.com/iotaledger/wasp/packages/chain"
Its imported twice. See next line.

2023-01-11 16:40 UTC, muXxer commented on packages/webapi/v2/services/offledger.go
> +	// state, err := ch.GetStateReader().LatestState()
Why is that here?

2023-01-11 16:40 UTC, muXxer commented on packages/webapi/v2/services/chain.go
> +	"github.com/iotaledger/wasp/packages/chain"
imported twice, see next line.

2023-01-11 16:40 UTC, muXxer commented on packages/solo/chain.go
> +	l1c, err := state.L1CommitmentFromAliasOutput(ao.GetAliasOutput())
Do we really want to panic the whole wasp node if one chain it follows has a state with invalid metadata?

2023-01-11 16:40 UTC, muXxer commented on packages/solo/evm.go
> +	return b.Chain.store.StateByIndex(blockIndex)
Should we also add the same logic like in the jsonrpc waspevmbackend?

```go
	latestState, err := b.chain.LatestState(chain.ActiveOrCommittedState)
	if err != nil {
		return nil, fmt.Errorf("couldn't get latest state: %s", err.Error())
	}
	if latestState.BlockIndex() == blockIndex {
		return latestState, nil
	}
	return b.chain.Store().StateByIndex(blockIndex)
```

2023-01-11 17:01 UTC, jorgemmsilva commented on packages/solo/chain.go
> +	l1c, err := state.L1CommitmentFromAliasOutput(ao.GetAliasOutput())
its not the "wasp node" its just solo, that's okay

2023-01-11 17:03 UTC, jorgemmsilva commented on packages/solo/evm.go
> +	return b.Chain.store.StateByIndex(blockIndex)
solo is just the test framework, this optimization wouldn't be a big benefit, rather keep the simpler code

2023-01-11 17:04 UTC, jorgemmsilva commented on packages/webapi/v2/services/chain.go
> +	"github.com/iotaledger/wasp/packages/chain"
well spotted!

2023-01-11 17:05 UTC, muXxer commented on packages/solo/chain.go
> +	l1c, err := state.L1CommitmentFromAliasOutput(ao.GetAliasOutput())
ah, true. ok feel free to ignore :D

2023-01-11 17:07 UTC, jorgemmsilva commented on packages/chain/node.go
> +		return latestConfirmedState, nil
this was written by Karolis, but my interpretation is that we might not have an "active state", but we must always have a `latestConfirmedState`

2023-01-11 17:09 UTC, muXxer commented on packages/solo/evm.go
> +	return b.Chain.store.StateByIndex(blockIndex)
Yeah I thought the benefit is not the optimization, but the fact that we "test" the exact same "optimization code" as we use in production.

2023-01-11 17:11 UTC, muXxer commented on packages/chain/node.go
> +		return latestConfirmedState, nil
But if we always must have a `latestConfirmedState`, why is there a fallback in `ActiveOrCommittedState` but not in `ConfirmedState`. Thats what I don't get :sweat_smile:

2023-01-11 17:18 UTC, jorgemmsilva commented on packages/chain/node.go
> +		return latestConfirmedState, nil
good point, maybe we can remove the fallback, or add it on the commented line.
@kape1395 wdyt?

2023-01-11 17:19 UTC, muXxer commented on packages/chain/node.go
> +		return latestConfirmedState, nil
@kape1395 can you elaborate? then we can merge this PR. :+1:

2023-01-11 19:37 UTC, kape1395 commented on packages/chain/node.go
> +		return latestConfirmedState, nil
Maybe that's a good point.
  - I was assuming the ConfirmedState case should be more strict, but probably it is correct enough to fall back to the store here.
  - Changed to use a fallback.
  - The situation, when the ConfirmedState is not yet available (apart from the Store) is the startup when the chain is started and the state is not yet fetched from the store.
  - Reorganized code a bit.

2023-01-11 19:56 UTC, muXxer approved these changes

2023-01-11 19:56 UTC, merged