Implement access nodes to api v2, some refactoring
iotaledger/wasp-legacy pull request #1667
Opened 2023-01-13 14:11 UTC by lmoe

2023-01-13 14:52 UTC, muXxer requested changes

2023-01-13 14:52 UTC, muXxer commented on packages/webapi/v2/controllers/chain/controller.go
> +	adminAPI.POST("chains/:chainID/access-node/:publicKey", c.addAccessNode, authentication.ValidatePermissions([]string{permissions.ChainWrite, permissions.PeeringWrite})).
This should be a `PUT` afaik

2023-01-13 15:14 UTC, muXxer requested changes

2023-01-13 15:14 UTC, muXxer commented on packages/webapi/v2/controllers/chain/access_nodes.go
> +	if err != nil {
```suggestion
	if err := c.nodeService.AddAccessNode(chainID, publicKey); err != nil {
```

2023-01-13 15:14 UTC, muXxer commented on packages/webapi/v2/controllers/chain/access_nodes.go
> +	if err != nil {
```suggestion
	if err := c.nodeService.DeleteAccessNode(chainID, publicKey); err != nil {
```

2023-01-13 15:14 UTC, muXxer commented on packages/webapi/v2/services/node.go
> +	if !ok {
```suggestion
	if _, ok := lo.Find(peers, func(p *peering.TrustedPeer) bool {
		return p.PubKey().Equals(publicKey)
	}); !ok {
```

2023-01-13 15:14 UTC, muXxer commented on packages/webapi/v2/services/node.go
> +	if err != nil {
```suggestion
	if _, err := n.chainRecordRegistryProvider.UpdateChainRecord(chainID, func(rec *registry.ChainRecord) bool {
		return rec.AddAccessNode(publicKey)
	}); err != nil {
```

2023-01-13 15:14 UTC, muXxer commented on packages/webapi/v2/services/node.go
> +	if err != nil {
```suggestion
	if _, err := n.chainRecordRegistryProvider.UpdateChainRecord(chainID, func(rec *registry.ChainRecord) bool {
		return rec.RemoveAccessNode(publicKey)
	}); err != nil {
```

2023-01-13 15:14 UTC, muXxer commented on packages/webapi/v2/params/decoder.go
> +	"github.com/iotaledger/wasp/packages/cryptolib"
Please configure your IDE to sort all iotaledger imports correctly.
For vscode use:
```json
    "gopls": {
        "formatting.local": "github.com/iotaledger"
    },
```

2023-01-13 15:14 UTC, muXxer commented on packages/webapi/v2/models/dks.go
> +	PeerPublicKeys [][]byte `json:"peerPublicKeys" swagger:"desc(Public keys of the nodes sharing the key.)"`
may mention `Hex encoded` here as well

2023-01-13 15:14 UTC, muXxer commented on packages/webapi/v2/models/dks.go
> +	PeerPublicKeys [][]byte `json:"peerPublicKeys" swagger:"desc(Public keys of the nodes sharing the key.)"`
also in the other fields like sharedPubKey etc

2023-01-13 15:33 UTC, lmoe commented on packages/webapi/v2/models/dks.go
> +	PeerPublicKeys [][]byte `json:"peerPublicKeys" swagger:"desc(Public keys of the nodes sharing the key.)"`
It's not hex encoded, it returns a byte array because I forgot to actually add the hex encoding.  

Will add this fix to the PR.

2023-01-16 14:48 UTC, muXxer approved these changes

2023-01-16 15:03 UTC, merged