Wal
iotaledger/wasp-legacy pull request #1686
Opened 2023-01-19 13:14 UTC by Juliusan

# Description of change

Wal is used to obtain a block. Also `rawBlocks` config parameter renamed to `wal` and made `wal` enabled by default.

## Type of change

- Enhancement (a non-breaking change which adds functionality)

## How the change has been tested

`make test`. New tests added and old ones improved to test the changes.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [x] I have followed the [contribution guidelines](https://wiki.iota.org/smart-contracts/contribute) for this project
- [x] I have performed a self-review of my own code
- [x] I have selected the `develop` branch as the target branch
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that new and existing unit tests pass locally with my changes

2023-01-19 14:08 UTC, jorgemmsilva commented on packages/util/equatable.go
> +
could this be used instead?
https://github.com/samber/lo#intersect

2023-01-19 14:09 UTC, jorgemmsilva commented on packages/util/equatable.go
> +
either that or `Contains`/`ContainsBy`

2023-01-19 14:14 UTC, jorgemmsilva requested changes

2023-01-19 14:14 UTC, jorgemmsilva commented on packages/chain/statemanager/smGPA/smGPAUtils/interface.go
> +	Delete(state.BlockHash) bool
can this be moved to a test file?

2023-01-19 14:14 UTC, jorgemmsilva commented on packages/chain/statemanager/smGPA/smGPAUtils/block_wal_mocked.go
> +}
can this be moved to a test file?

2023-01-19 14:14 UTC, jorgemmsilva commented on packages/chain/statemanager/smGPA/smGPAUtils/block_wal_db.go
> +// Function is not used currently
remove it?

2023-01-19 14:14 UTC, jorgemmsilva commented on packages/chain/statemanager/smGPA/smGPAUtils/block_wal.go
> +}
should this return an error, instead of just logging warns?

2023-01-19 16:55 UTC, dessaya commented on packages/util/equatable.go
> +
+1 for reusing `lo` whenever possible. In fact, I think the `Equatable` interface can be dropped because it is implemented by two types that are arrays, so they already implement the `comparable` constraint. So `lo.Intersect` and friends should work.

2023-01-19 19:09 UTC, Juliusan commented on packages/chain/statemanager/smGPA/smGPAUtils/block_wal_mocked.go
> +}
No. These methods describe `mockedBlockWAL` struct and they belong together. It would be less clear if we scatter the methods all over the code. And `Contents` is i in the main interface anyway.

2023-01-19 19:10 UTC, Juliusan commented on packages/chain/statemanager/smGPA/smGPAUtils/block_wal_db.go
> +// Function is not used currently
Will do. I spent on it plenty of time and committed it, so it was a shame to remove it :-)

2023-01-19 19:23 UTC, Juliusan commented on packages/chain/statemanager/smGPA/smGPAUtils/block_wal.go
> +}
This function was needed for the method, which is not used and will be removed. For it it was enough to have a method, that silently returns what it can. I think, I'll simply drop this method.

2023-01-19 19:33 UTC, Juliusan commented on packages/util/equatable.go
> +
Yes, `Equatable` interface is only used for array types. But it is more flexible than `comparable` constraint. It could be used for any struct, which implement `Equals` method telling how to decide which two objects are equal. I can remove it for now though.

2023-01-19 19:51 UTC, dessaya commented on packages/util/equatable.go
> +
If it is unused I'd vote for removing it, just so we have less code to maintain.

If you decide to keep it, I suggest:

* Renaming the interface, since I think "equatable" is not a real word (is it?). Maybe `Comparable`, or `Eq` like Haskell.

* Changeing the interface to:

```
type Eq[T any] interface {
  Equals(T other) bool
}
```

so that the `Equals` method can accept an object of the same type. Then:

```
func Intersection[T Eq[T]](objects1, objects2 []T) []T {
  ...
}
```

2023-01-20 15:24 UTC, jorgemmsilva approved these changes

2023-01-20 15:24 UTC, jorgemmsilva commented on packages/chain/statemanager/smGPA/smGPAUtils/block_cache_rapid_no_wal_test.go
> +	require.Equal(t, len(bcnwtsmT.blocksInCache), len(lo.Uniq(bcnwtsmT.blocksInCache)))
I know this is from before, but this is such a weird name: `bcnwtsmT`, why not just `b`? :joy:

2023-01-20 16:00 UTC, Juliusan commented on packages/chain/statemanager/smGPA/smGPAUtils/block_cache_rapid_no_wal_test.go
> +	require.Equal(t, len(bcnwtsmT.blocksInCache), len(lo.Uniq(bcnwtsmT.blocksInCache)))
Shortened from "BlockCacheNoWalTestStateMachine" :-D I would prefer "this", but it is prohibited :-) I rarely use one letter variables.

2023-01-20 16:02 UTC, jorgemmsilva commented on packages/chain/statemanager/smGPA/smGPAUtils/block_cache_rapid_no_wal_test.go
> +	require.Equal(t, len(bcnwtsmT.blocksInCache), len(lo.Uniq(bcnwtsmT.blocksInCache)))
agree on letter variables is bad in general, but for receivers is very intuitive. Also easier to write than `zlxkTcNziolkj` :trollface:

2023-01-21 07:04 UTC, merged