refactor: avoid possible memory leaks with time.After
iotaledger/wasp-legacy pull request #1699
Opened 2023-01-23 04:55 UTC by ivange94

# Description of change

Avoid potential memory leaks with `timer.After`. 

Fixes https://github.com/iotaledger/wasp/issues/1464

2023-01-23 09:06 UTC, muXxer requested changes
Can you also fix the missing `time.After` in:
```
packages/peering/group/group.go
packages/dkg/proc.go
packages/chain/statemanager/smGPA/smGPAUtils/block_cache.go
packages/chain/statemanager/smGPA/smGPAUtils/time_provider_default.go
packages/chain/cons/gr/gr.go
```

2023-01-23 09:06 UTC, muXxer commented on tools/cluster/cluster.go
> +		defer timeutil.CleanupTimer(delay)
you don't need to change the logic in the cluster tests or test cases, because its irrelevant for the test cases and is harder to read.

this change here introduces a resource leak because of the defer in the loop, please revert.

2023-01-23 09:06 UTC, muXxer commented on tools/cluster/cluster.go
> +		delay := time.NewTimer(5 * time.Second)
you don't need to change the logic in the cluster tests or test cases, because its irrelevant for the test cases and is harder to read.

this change here introduces a resource leak because of the defer in the loop, please revert.

2023-01-23 09:06 UTC, muXxer commented on packages/peering/lpp/lppNetImpl.go
> +		delay := time.NewTimer(maintenancePeriod)
This introduces a resource leak.
IMO you should put the whole code in an inline func, and then call that in the for loop.
This way you can do the `defer` in the inline func.

2023-01-24 06:07 UTC, ivange94 commented on packages/peering/lpp/lppNetImpl.go
> +		delay := time.NewTimer(maintenancePeriod)
After looking at this piece again, the `defer` was not necessary. Right now I just clean up the timer inside 
`case <-stopCh`. So if the timer fires before the stop signal is sent, the `timer.C` is read. And since a stop signal has not being sent, the loop restarts and a new timer is initialized which is how the original logic was. 

Using `defer` in an inline function, I ended up with this 
````
for {
	stop := func() bool {
		delay := time.NewTimer(maintenancePeriod)

		select {
		case <-delay.C:
			n.peersLock.RLock()
			for _, p := range n.peers {
				p.maintenanceCheck()
			}
			n.peersLock.RUnlock()
			return false
		case <-stopCh:
			timeutil.CleanupTimer(delay)
			return true
		}
	}()
	if stop {
		return
	}
}
````
To prevent the loop from running indefinitely even after the stop signal has been received, I had to introduce a new variable to check the return status of the inline function. I find the former version much more readable and unless I missed something, the both have the same effect.

2023-01-24 14:54 UTC, ivange94 commented
@muXxer concerning
>Can you also fix the missing time.After in:

>packages/peering/group/group.go
packages/dkg/proc.go
packages/chain/statemanager/smGPA/smGPAUtils/block_cache.go
packages/chain/statemanager/smGPA/smGPAUtils/time_provider_default.go
packages/chain/cons/gr/gr.go

1. `block_cache.go` does't use the package level function `time.After` but the struct function `Time.After` which returns a boolean so I'm not sure what you mean.

2. `time_provider_default.go` implements [TimeProvider](https://github.com/iotaledger/wasp/blob/develop/packages/chain/statemanager/smGPA/smGPAUtils/interface.go#L21) and changing the method implementation forces me to change the interface definition which intend forces me to modify a lot of test cases. And as you mentioned, fixing this in tests adds little value but makes the code much harder to read.

2023-02-01 16:35 UTC, ivange94 commented
Closing this. Will open a new one with a cleaner commit history.

2023-02-01 16:35 UTC, closed without merging