Update local setup docs
iotaledger/wasp-legacy pull request #1872
Opened 2023-02-11 16:34 UTC by ivange94

# Description of change
Update local setup docs

2023-02-12 17:46 UTC, jorgemmsilva requested changes

2023-02-12 17:46 UTC, jorgemmsilva commented on tools/local-setup/README.md
> +
this is not true. the local setup should use an image from dockerhub.

2023-02-12 17:46 UTC, jorgemmsilva commented on tools/local-setup/README.md
we should remove this since we took wasp-cli out of the main image.
Rather there should be a link to down the latest release from github

2023-02-12 18:07 UTC, ivange94 commented on tools/local-setup/README.md
> +
Then you might want to check what's on dockerhub. I can reproduce this error every time if I clean up all images and containers with `docker system prune -a` and just do a `docker compose up` without building first and this error pops up. Here's the log
```
   self.warnings.warn(
local-setup-hornet-nest-1  | 2023-02-11 02:36:59,238 CRIT Server 'unix_http_server' running without any HTTP authentication checking
wasp                       | panic: unable to initialize app: no version given
wasp                       |
wasp                       | goroutine 1 [running]:
wasp                       | github.com/iotaledger/hive.go/core/app.New({0x2dad45d, 0x4}, {0x0, 0x0}, {0xc000c43e78, 0x4, 0x1a0?})
wasp                       |    /go/pkg/mod/github.com/iotaledger/hive.go/core@v1.0.0-rc.2.0.20230120131747-b65c9cb22ea9/app/app.go:72 +0x618
wasp                       | github.com/iotaledger/wasp/core/app.App()
wasp                       |    /scratch/core/app/app.go:38 +0x2f7
wasp                       | main.main()
wasp                       |    /scratch/main.go:8 +0x19
wasp exited with code 2
wasp                       | panic: unable to initialize app: no version given
```
But I will close this as a user error just incase the problem is my system.

2023-02-12 18:53 UTC, jorgemmsilva commented on tools/local-setup/README.md
> +
I'm not saying the image is working :trollface: 

Just saying:
>You need to build the wasp container using...
is not correct.
We want this to be plug-and-play, no need for the users to rebuild wasp image.

we should fix the dockerhub image if that is broken.

2023-02-15 03:24 UTC, ivange94 commented
This problem no longer exists. I just did a `docker system prune -a` and then `docker compose up` and the version is set properly so closing this now.

2023-02-15 03:24 UTC, closed without merging