wasp-cli convinience method for registerERC20NativeToken
iotaledger/wasp-legacy pull request #1973
Opened 2023-02-20 10:31 UTC by ivange94

# Description of change

wasp-cli convinience method for registerERC20NativeToken

2023-02-20 17:08 UTC, dessaya approved these changes

2023-02-20 17:08 UTC, dessaya commented on tools/wasp-cli/corecontractscmd/cmd.go
> +		Use:   "call <contract>",
This `chain call` command is a bit wierd considering that most other subcommands under `chain` are already calling core contracts. I think instead of:

```
wasp-cli chain call evm register-erc20-native-token
```

it would be simpler and more consistent like:

```
wasp-cli chain register-erc20-native-token
```

2023-02-20 17:08 UTC, dessaya commented on tools/wasp-cli/corecontractscmd/evm.go
> +			chaincmd.PostRequest(n, c, evm.Contract.Hname().String(), "registerERC20NativeToken", params, true, adjustStorageDeposit)
Maybe use the api client like other commands, for consistency?

2023-02-20 18:20 UTC, ivange94 commented on tools/wasp-cli/corecontractscmd/evm.go
> +			chaincmd.PostRequest(n, c, evm.Contract.Hname().String(), "registerERC20NativeToken", params, true, adjustStorageDeposit)
There's no API for full entry point calls just view calls. I was going to add that then I came across the `postRequest` command and thought maybe it'll be best to reuse it. I can add the api endpoint for this and refactor this command in another PR.

2023-02-21 01:33 UTC, muXxer requested changes

2023-02-21 01:33 UTC, muXxer commented on tools/wasp-cli/chain/register-erc20-native-token.go
> +			postRequest(node, chain, evm.Contract.Hname().String(), "registerERC20NativeToken", params, true, adjustStorageDeposit)
How are parameters like `foundrySerialNumber`, `tokenName`, `tickerSymbol`, `tokenDecimals` and `allowance` passed to the actual command? I don't get it :innocent:

2023-02-21 05:28 UTC, ivange94 commented on tools/wasp-cli/chain/register-erc20-native-token.go
> +			postRequest(node, chain, evm.Contract.Hname().String(), "registerERC20NativeToken", params, true, adjustStorageDeposit)
Nice catch. That should be fixed now.

2023-02-21 14:08 UTC, muXxer approved these changes

2023-02-21 14:08 UTC, merged