fix: Add network check in wasp-cli
iotaledger/wasp-legacy pull request #1988
Opened 2023-02-21 13:44 UTC by howjmay

2023-02-21 14:01 UTC, muXxer requested changes

2023-02-21 14:01 UTC, muXxer commented on tools/wasp-cli/cli/config/config.go
> +	chainID, err := isc.ChainIDFromString(configChainID)
IMO we should do that check in a bit cleaner way, to understand whats going on.

I would use the networkPrefix parameter from the `networkPrefix, addr, err := iotago.ParseBech32(bech32)` , which is the HRP, and compare it with the `parameters.L1().Protocol.Bech32HRP`.

2023-02-22 08:16 UTC, howjmay commented on tools/wasp-cli/cli/config/config.go
> +	chainID, err := isc.ChainIDFromString(configChainID)
Fixed. However, I am not sure if the current error message is a good one

2023-02-23 18:25 UTC, muXxer approved these changes

2023-02-23 18:25 UTC, muXxer commented on tools/wasp-cli/cli/config/config.go
> +		err = fmt.Errorf("target network not matches wasp-cli config")
```suggestion
		err = fmt.Errorf("target network of the L1 node does not match the wasp-cli config")
```

2023-02-23 18:26 UTC, merged