Add websockets v2
iotaledger/wasp-legacy pull request #2003
Opened 2023-02-22 17:22 UTC by lmoe

# Description of change
Updates the websocket to use the API models.

Events, commands and validation are now in separate classes, hopefully to make it easier to extend
Publisher has separate event types to support proper model mapping
ISCEvent is now generic throughout the pipeline
wasmlib websocket clients were refactored

## Links to any relevant issues

Be sure to reference any related issues by adding `fixes issue #`.

## Type of change

Choose a type of change, and delete any options that are not relevant.

- Bug fix (a non-breaking change which fixes an issue)
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any relevant configurations.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the [contribution guidelines](https://wiki.iota.org/smart-contracts/contribute) for this project
- [ ] I have performed a self-review of my own code
- [ ] I have selected the `develop` branch as the target branch
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2023-02-22 18:16 UTC, BugFreeSoftware approved these changes

2023-02-23 20:31 UTC, muXxer requested changes

2023-02-23 20:31 UTC, muXxer commented on packages/publisher/events.go
> +	return fmt.Sprintf("%s | %s (%s): %v", e.ChainID, issuerStr, e.Kind, e.Payload)
do we really need to print the payload here?

2023-02-23 20:31 UTC, muXxer commented on packages/publisher/events.go
>  			// TODO should be the contract Hname, but right now events are just stored as strings.
are these TODOs still a thing?

2023-02-23 20:31 UTC, muXxer commented on plugins/webapi/params.go
> +		MaxTopicSubscriptionsPerClient int           `default:"0" usage:"defines the max amount of subscriptions per client. 0 = deactivated (default)"`
Please run the `/scripts/gendoc.sh` script and commit the changes to the default config and the documentation that is generated.

2023-02-23 20:31 UTC, muXxer commented on plugins/webapi/component.go
>  			hub,
You don't need to pass the hub anymore to the Init.

2023-02-23 20:31 UTC, muXxer commented on packages/publisher/publisher.go
> +// NOTE: Do not Block the caller!
find and replace? :D

2023-02-23 20:31 UTC, muXxer commented on packages/publisher/publisher.go
> +// NOTE: Do not Block the caller!
find and replace? :D

2023-02-23 20:31 UTC, muXxer commented on packages/publisher/publisher.go
> +// NOTE: Do not Block the caller!
find and replace? :D

2023-02-23 20:31 UTC, muXxer commented on packages/webapi/websocket/commands/commandmanager.go
> +	if errors.Is(err, ErrFailedToDeserializeCommand) {
Use a switch case here :+1:

2023-02-24 11:55 UTC, lmoe commented on packages/publisher/events.go
>  			// TODO should be the contract Hname, but right now events are just stored as strings.
Yeah the events you emit from contracts are just strings. And they not only contain a random string but appended data like the Hname of the contract and so on. We could split the string in the publisher and get the values out of it. But it's pretty hacky and would rather avoid this.

2023-02-24 13:29 UTC, merged