Mark math/rand sources as pseudo RNG
iotaledger/wasp-legacy pull request #2011
Opened 2023-02-23 21:48 UTC by muXxer

2023-02-23 21:49 UTC, muXxer commented on packages/trie/trie_test.go
> +	rnd := util.NewPseudoRand(1)
@dessaya can you maybe answer this? wouldn't it be better to have a random seed for the RNG? Or was this done for a specific reason?

2023-02-23 22:07 UTC, dessaya commented on packages/trie/trie_test.go
> +	rnd := util.NewPseudoRand(1)
This code is originally by Evaldas I think.
I think the intention is to make the test as deterministic as possible, which I think is a good idea in general. So yes, seed it with anything that is constant.

2023-02-23 22:09 UTC, dessaya approved these changes
I'm not sure I like these "pseudo" all over the place. I mean, we already know random numbers are not really random... Even cryptographically secure RNGs are pseudo-random, so...

2023-02-23 22:09 UTC, kape1395 requested changes
I will review it tomorrow.

2023-02-23 22:10 UTC, muXxer commented on packages/trie/trie_test.go
> +	rnd := util.NewPseudoRand(1)
Alright, then I will remove the TODO and leave it as it is!
I was just wondering because we once had the problem that we didn't found a bug in our codebase, because the test used a fixed seed for the RNG, so the tests were deterministic, but they never hit that one case where the error occurred :laughing:

2023-02-23 22:12 UTC, muXxer commented
> I'm not sure I like these "pseudo" all over the place. I mean, we already know random numbers are not really random... Even cryptographically secure RNGs are pseudo-random, so...

I thought `Pseudo` is a better word than `CryptoInsecureRand` :trollface:

2023-02-24 08:29 UTC, kape1395 approved these changes

2023-02-24 08:49 UTC, merged