refactor: remove init tx
iotaledger/wasp-legacy pull request #2034
Opened 2023-02-28 12:35 UTC by jorgemmsilva

this removes the need for the "initTx", and by simplifying the process of chain deployment (to a single output), reduces the number of edge cases and allows requests to be sent right away to the chain.

- core contracts don't have constructors anymore, they instead init the state using information in the origin alias output
- removes descrition from the chain and corecontracts (not from from wasm contracts to not pile up more changes)
- refactors the "blockcontext" so that we don't need the "privileged sandbox methods" for that anymore

further work:
- chain Owner could be derived from the chain govenor - to be discussed
- SD assumptions need to be removed and we need to be able to handle protocol changes on L1, including min SD increase ([issue](https://github.com/iotaledger/wasp/issues/2002))
- controlAddresses in blocklog seem pretty useless and can be removed ([issue](https://github.com/iotaledger/wasp/issues/2033))
- remove description from wasm contracts

TODO:
@kape1395 please take a look at `(cni *chainNodeImpl) handleAliasOutput`. I think this is pretty okay, but please do confirm you agree with initializing the chain state there.

2023-02-28 12:40 UTC, kape1395 requested changes
Do not merge until I'm done with

> @kape1395 please take a look at (cni *chainNodeImpl) handleAliasOutput. I think this is pretty okay, but please do confirm you agree with initializing the chain state there

2023-02-28 13:51 UTC, dessaya reviewed
Here: https://github.com/iotaledger/wasp/blob/develop/packages/vm/vmcontext/migrations.go#L14

Maybe the initialization of the schema version should be done when initializing the root contract instead?

2023-02-28 13:51 UTC, dessaya commented on packages/apilib/deploychain.go
> +	dscr string,
Is this `dscr` parameter still needed?

2023-02-28 13:51 UTC, dessaya commented on packages/evm/jsonrpc/evmchain.go
>  	// the first EVM block (number 0) is "minted" at ISC block index 1 (init chain)
This comment is now outdated?

```suggestion
	// the first EVM block (number 0) is "minted" at ISC block index 0
```

2023-02-28 13:51 UTC, dessaya commented on packages/origin/origin.go
> +	evmChainID := evmtypes.MustDecodeChainID(initParams.MustGet(evm.FieldChainID), evm.DefaultChainID)
Does this work correctly with `wasp-cli`? The EVM init params were prefixed with `root.ParamEVM` to avoid collisions with init params of other core contracts.

Maybe we should place all init param keys on the same file.

2023-02-28 13:51 UTC, dessaya commented on packages/state/db.go
> -	KeyChainID = "\x00"
The chain ID is stored somewhere else now?

2023-02-28 13:51 UTC, dessaya commented on packages/state/state_test.go
> +package state_test
Is this standard? There are now 2 different packages on the same folder :thinking: 

Also, why change this?

2023-02-28 13:51 UTC, dessaya commented on packages/transaction/origintx.go
> +	// }
intentionally left commented out?

2023-02-28 14:53 UTC, jorgemmsilva commented on packages/state/state_test.go
> +package state_test
this is standard, to test the current package as a blackbox. 
https://pkg.go.dev/testing

don't remember in particular now, but this is a good practice overall and I think we should do this where possible to avoid polluting the main package with testing functions

2023-02-28 14:56 UTC, jorgemmsilva commented on packages/state/db.go
> -	KeyChainID = "\x00"
we don't need it. It can always be derived from somewhere else. the node knows what chain is running the task on.
Also the chainID is not known before issuing the originTx, meaning that if it is part of the state, we couldn't calculate the origin commitment to include it in the output.

2023-02-28 15:16 UTC, jorgemmsilva commented on packages/origin/origin.go
> +	evmChainID := evmtypes.MustDecodeChainID(initParams.MustGet(evm.FieldChainID), evm.DefaultChainID)
good point :+1:

2023-02-28 16:42 UTC, dessaya commented on packages/origin/origin.go
> +	evmChainID := evmtypes.MustDecodeChainID(initParams.MustGet(evm.FieldChainID), evm.DefaultChainID)
I think this function should be removed now:
https://github.com/iotaledger/wasp/blob/develop/packages/vm/core/root/interface.go#L41

2023-02-28 16:58 UTC, dessaya approved these changes

2023-03-08 08:57 UTC, kape1395 requested changes

2023-03-08 08:57 UTC, kape1395 commented on packages/chain/node.go
> +	cni.log.Debugf("handleAliasOutput, aliasOutput[StateIndex=%v].ID=", aliasOutput.GetStateIndex(), aliasOutput.OutputID().ToHex())
This debug duplicates the one above. And AliasOutpitWithID.String() prints also the stateIndex, so this can be just removed.

2023-03-08 08:57 UTC, kape1395 commented on packages/chain/node.go
> +	if aliasOutput.GetStateIndex() == 0 {
I want to move the internals of this `if` to some function, but I am not sure in which package. `state` or `origin`?

2023-03-08 08:57 UTC, kape1395 commented on packages/chain/node.go
> +		if originMetadata := aliasOutput.GetAliasOutput().FeatureSet().MetadataFeature(); originMetadata != nil {
This place is probably OK, but we have to make sure the origin state is also downloadable in the statemgr. Have you done something about that?

2023-03-08 08:57 UTC, kape1395 commented on packages/chain/node_test.go
> +			// TODO these "unreliable" tests are crazy, they either succeed in 10~20s or run forever...
Don't comment them out. This can hide error.
Have you tried to increase retry periods?

2023-03-08 08:57 UTC, kape1395 commented on packages/chain/statemanager/smGPA/state_manager_gpa.go
> +					stateDraft = smT.store.NewOriginStateDraft()
Is `NewOriginStateDraft` still valid and meaningful?
Should it take the AO as a parameter?

2023-03-08 08:57 UTC, kape1395 commented on packages/evm/jsonrpc/evmchain.go
> +	return uint32(n), nil
Why has this changed?

2023-03-08 09:13 UTC, jorgemmsilva commented on packages/chain/node.go
> +	if aliasOutput.GetStateIndex() == 0 {
I tried that, but started getting import cycles. This works and it's not too extensive imo

2023-03-08 09:14 UTC, jorgemmsilva commented on packages/chain/node.go
> +		if originMetadata := aliasOutput.GetAliasOutput().FeatureSet().MetadataFeature(); originMetadata != nil {
Yep, done and tested

2023-03-08 09:15 UTC, jorgemmsilva commented on packages/chain/node_test.go
> +			// TODO these "unreliable" tests are crazy, they either succeed in 10~20s or run forever...
These hang for a really really really long time. I saw the same issue happening in develop. Doesn't seem like a good test to have if we want to "speed up tests"

2023-03-08 09:16 UTC, jorgemmsilva commented on packages/evm/jsonrpc/evmchain.go
> +	return uint32(n), nil
Now Evm chain block number == ISC block number, they both start at origin.

2023-03-08 09:16 UTC, jorgemmsilva commented on packages/chain/statemanager/smGPA/state_manager_gpa.go
> +					stateDraft = smT.store.NewOriginStateDraft()
This is just to apply the origin block when syncing

2023-03-08 09:43 UTC, kape1395 commented on packages/chain/node_test.go
> +			// TODO these "unreliable" tests are crazy, they either succeed in 10~20s or run forever...
But these tests are essential. They check how the chain copes with connection drops, message reorderings, duplicated messages, etc.

2023-03-08 11:26 UTC, kape1395 approved these changes

2023-03-08 11:26 UTC, merged