fix: Show error message when config file not in the default location
iotaledger/wasp-legacy pull request #2073
Opened 2023-03-08 09:50 UTC by howjmay

2023-03-08 12:50 UTC, dessaya commented on tools/wasp-cli/waspcmd/cmd.go
> +	waspSettings := waspConfigSubTree.AllSettings()
The error message can be misleading, since you can have a `wasp-cli.json` with a missing `wasp` section.

```suggestion
	waspSection := viper.Sub("wasp")
	waspSettings := map[string]interface{}{}
	if waspSection != nil {
		waspSettings = waspSection.AllSettings()
	}
```

2023-03-08 15:22 UTC, dessaya approved these changes

2023-03-10 12:36 UTC, dessaya reviewed
Does `wasp-cli --help` still work?

2023-03-10 13:27 UTC, howjmay commented
@dessaya yes, `help` command are triggered by `Run`, but configure files are used by `PersistentPreRun`. Therefore, this PR won't block calling `help`.
See the following clip. 

```go
return &cobra.Command{
    Version: waspVersion,
    Use:     "wasp-cli",
    Short:   "wasp-cli is a command line tool for interacting with Wasp and its smart contracts.",
    Long: `wasp-cli is a command line tool for interacting with Wasp and its smart contracts.
NOTE: this is alpha software, only suitable for testing purposes.`,
    PersistentPreRun: func(cmd *cobra.Command, args []string) {
        config.Read()
    },
    Run: func(cmd *cobra.Command, args []string) {
        cmd.Help() //nolint:errcheck
    },
}
```

2023-03-10 14:04 UTC, dessaya requested changes
Actually `PersistentPreRun` is always executed before `Run`. If you provide `--help`, neither `PreRun` nor `Run` are executed.

So these work:
* `wasp-cli --help`
* `wasp-cli chain --help`

But these do not work anymore (previously they showed the help message, now they just show the error):
* `wasp-cli`
* `wasp-cli chain`

Also, `--help` shows:

```
Available Commands:
  ...
  help              Help about any command
```

but `wasp-cli help` does not work anymore.

Also, some subcommands like `decode-metadata` do not require any configuration, and now they do not work anymore unless you do `init` first.

2023-03-10 17:12 UTC, howjmay commented
@dessaya May I ask what are the commands that don't need config file?
I think if there are multiple commands, then may be I just check each of them everytime they call `viper` that will bring less change

2023-03-10 17:45 UTC, dessaya commented
Sorry, I don't know every command and subcommand.

What is the root issue that you are trying to solve? Maybe there is a simpler approach.

2023-03-10 18:33 UTC, howjmay commented
@dessaya The root issue was a simple one. I just found if `wasp-cli.json` doesn't exist then a `nil pointer` error will be returned. And I thought this should not be a proper behavior.  So I can protect all the `viper.Sub()` from this condition. This solution may not look pretty, and the error message is not the best (it will only say a certain field in `wasp-cli.json` doesn't exist), but at least remove the aformentioned error

2023-03-10 18:41 UTC, dessaya commented
Then IMO it is better to just check for nil every time we call `viper.Sub()`. It's only 3 places, so it is not a big change. I understand it is uglier, but this way we don't break functionality.

2023-03-11 18:53 UTC, dessaya approved these changes

2023-03-11 18:53 UTC, dessaya commented on tools/wasp-cli/chain/flag.go
> +	chainSettings := configSubTree.AllSettings()
```suggestion
    chainSettings := map[string]interface{}{}
	if viper.Sub("chains") != nil {
		chainSettings = viper.Sub("chains").AllSettings()
	}
```

This way we fall back nicely into the `case 0` below. The error message there is good enough.

2023-03-11 18:53 UTC, dessaya commented on tools/wasp-cli/cli/init/checkversions.go
> +				log.Fatal("`wasp` field or config file doesn't exist")
```suggestion
				log.Fatal("no wasp node configured, you can add a node with `wasp-cli wasp add <name> <api url>`")
```

2023-03-11 18:53 UTC, dessaya commented on tools/wasp-cli/waspcmd/cmd.go
> +	waspSettings := configSubTree.AllSettings()
```suggestion
    waspSettings := map[string]interface{}{}
	if viper.Sub("wasp") != nil {
		waspSettings = viper.Sub("chains").AllSettings()
	}
```

falling back to `case 0` below.

2023-03-12 11:13 UTC, dessaya approved these changes

2023-03-14 11:03 UTC, jorgemmsilva approved these changes

2023-03-18 19:36 UTC, BugFreeSoftware commented
Closed as duplicate after I encountered and fixed the nil pointer issue and more.
This fix still contains bugs that are fixed in my PR #2128

2023-03-18 19:36 UTC, closed without merging