Use ShrinkingMaps for long living maps to avoid memleaks - part 1
iotaledger/wasp-legacy pull request #2087
Opened 2023-03-10 16:17 UTC by muXxer

2023-03-14 12:44 UTC, dessaya commented on packages/kv/buffered/mutation.go
> +	Dels *shrinkingmap.ShrinkingMap[kv.Key, struct{}]
I don't think there are any long-lasting instances of `Mutation`, so why this change?
Isn't this premature optimization? (Which we all know is the root of all evil?).

Is there a measureable improvement? Are there no drawbacks (apart from the increased complexity)? For example I see that `for range` loops now involve a function call + a closure. Isn't that less efficient?

2023-03-14 12:49 UTC, dessaya requested changes

2023-03-14 12:49 UTC, dessaya commented on packages/trie/kvimpl.go
> +	m *shrinkingmap.ShrinkingMap[string, []byte]
This thing is only used in tests, so no need for the change.

2023-03-14 12:52 UTC, muXxer commented on packages/trie/kvimpl.go
> +	m *shrinkingmap.ShrinkingMap[string, []byte]
Cool, I can revert that change. Can we move all "test-only" related packages maybe to `packages/testutil` ?

2023-03-14 12:54 UTC, muXxer commented on packages/kv/buffered/mutation.go
> +	Dels *shrinkingmap.ShrinkingMap[kv.Key, struct{}]
I wasn't 100% sure about the lifetime of the `Mutations` struct, so I also changed it.
I can revert that change if you want.

2023-03-14 12:57 UTC, dessaya commented on packages/trie/kvimpl.go
> +	m *shrinkingmap.ShrinkingMap[string, []byte]
I don't think it would make sense here, because this `InMemoryKVStore` only makes sense for the `trie` package; it's not useful anywhere else. It could even be package private.

2023-03-14 13:02 UTC, dessaya commented on packages/kv/buffered/mutation.go
> +	Dels *shrinkingmap.ShrinkingMap[kv.Key, struct{}]
I'd say let's revert unless there is a measureable improvement.

The same goes for the rest of the PR: in general it is increasing complexity, so IMO it should be justified. but I'm not familiar with every package so I'd ask Jorge, Karolis, Julius, etc.

2023-03-14 13:39 UTC, dessaya approved these changes

2023-03-14 13:41 UTC, muXxer commented on packages/kv/buffered/mutation.go
> +	Dels *shrinkingmap.ShrinkingMap[kv.Key, struct{}]
Reverted :+1:

2023-03-14 13:41 UTC, muXxer commented on packages/trie/kvimpl.go
> +	m *shrinkingmap.ShrinkingMap[string, []byte]
Reverted and moved to `trie/test` :+1:

2023-03-14 14:48 UTC, jorgemmsilva approved these changes
In a handful of places this change makes sense, but using this everywhere is kinda extreme.
We're adding a bunch of mutexes and cleanup logic where it is not even clear that there is a leak

let's wait for Karolis and Julius input before merging

2023-03-14 14:48 UTC, jorgemmsilva commented on packages/vm/processors/cache.go
> -	processors map[hashing.HashValue]isc.VMProcessor
a new processors Cache created every time a new consensus instance starts, so I wouldn't say this is exactly "long living"

2023-03-14 14:48 UTC, jorgemmsilva commented on packages/chain/chainMgr/chainMgr.go
> +	cmtLogs                 map[iotago.Ed25519Address]*cmtLogInst                            // All the committee log instances for this chain.
shouldn't this also be a shrinking map?

2023-03-14 14:48 UTC, jorgemmsilva commented on packages/chain/cmtLog/var_log_index.go
> +	consAggrAO *shrinkingmap.ShrinkingMap[LogIndex, *isc.AliasOutputWithID] // Recent outputs, to filter L1ReplacedBaseAliasOutput.
think this `varLogIndexImpl` obj is only live during 1 consensus "log index", meaning it shouldn't be "long living"

2023-03-14 14:48 UTC, jorgemmsilva commented on packages/chains/accessMgr/amDist/accessMgrDist.go
> +	chains           *shrinkingmap.ShrinkingMap[isc.ChainID, *accessMgrChain] // State for each chain.
these shouldn't hold more than a handful of elements, I doubt its worth it to make the change

2023-03-14 16:09 UTC, muXxer commented on packages/chain/chainMgr/chainMgr.go
> +	cmtLogs                 map[iotago.Ed25519Address]*cmtLogInst                            // All the committee log instances for this chain.
I couldn't find a `delete` call for this map, so I didn't change to a `shrinkingmap`

2023-03-15 14:28 UTC, jorgemmsilva commented on packages/chain/chainMgr/chainMgr.go
> +	cmtLogs                 map[iotago.Ed25519Address]*cmtLogInst                            // All the committee log instances for this chain.
I guess this turns into a question to @kape1395 : shouldn't we delete the cmtLogs at some point? :sweat_smile:

2023-03-23 17:43 UTC, merged