Fix: get balance from webapi receives URLencoded param. It does not r…
iotaledger/wasp-legacy pull request #2232
Opened 2023-03-31 12:40 UTC by ScovottoDavide

When requesting L2 account balances (hname@addr) from the wasp-dashboard the decoding of the AgentID would fail because it receives the URLencoded parameter. For example:

wasp-dashboards requests balance for 000000@L1addr --> the wasp node tries to retrieve the balance of 000000%40L1addr.

This is what the server returns:
 ```
{
     "Message": "Invalid property: agentID",
     "Error": "NewAgentIDFromString: wrong format"
}
```

This has been tested on:
`wasp version 0.6.0-alpha.7`
`wasp-cli version 0.6.0-alpha.7`

2023-04-02 16:56 UTC, dessaya requested changes

2023-04-02 16:56 UTC, dessaya commented on packages/webapi/params/decoder.go
> +	agentID, err := isc.NewAgentIDFromString(tmp_agent)
Thank you for the contribution @ScovottoDavide !

Unfortunately I don't think this is the correct solution, since it does not fix the root cause. The URL-encoded parameter should be decoded by the http engine, and for some reason that's not the case. We have to investigate that (#2076).

2023-04-02 23:15 UTC, ScovottoDavide commented on packages/webapi/params/decoder.go
> +	agentID, err := isc.NewAgentIDFromString(tmp_agent)
@dessaya Yes that is odd. 
Maybe a generic `url.PathUnescape(e.Param(ParamAgentID))` could temporary solve the problem. I'm locally running a wasp node like this. 
Anyway, thank you!

2023-04-03 12:23 UTC, jorgemmsilva requested changes

2023-04-03 12:23 UTC, jorgemmsilva commented on tools/local-setup/docker-compose.yml
> -  ###############
why is this PR removing hornet-nest from here?

2023-04-03 13:30 UTC, ScovottoDavide commented on tools/local-setup/docker-compose.yml
> -  ###############
@jorgemmsilva Sorry, my bad. I modified the compose because I already had a private tangle running. I replaced it with the original yaml file.

2023-05-11 16:10 UTC, jorgemmsilva commented
Closing this as it was already fixed by @lmoe .

Thank you @ScovottoDavide for bringing this issue up :raised_hands:

2023-05-11 16:10 UTC, closed without merging