test: Add corecontract tests
iotaledger/wasp-legacy pull request #2246
Opened 2023-04-02 08:02 UTC by howjmay

2023-04-02 17:06 UTC, dessaya commented on packages/vm/core/accounts/impl_views.go
> +		ParamNFTAmount: codec.EncodeUint32(cnt),
Why this change?
The current implementation is O(1) and this will make it O(n).

2023-04-03 06:18 UTC, howjmay commented on packages/vm/core/accounts/impl_views.go
> +		ParamNFTAmount: codec.EncodeUint32(cnt),
But the current implementation didnt really set the NFT with collection successfully, so with the previous implementation, I retrieve `nil`. I don't know how to fix this, so I presented this workaround temporarily

2023-04-03 13:32 UTC, dessaya commented on packages/vm/core/accounts/impl_views.go
> +		ParamNFTAmount: codec.EncodeUint32(cnt),
Can you clarify? What do you mean by "set the NFT with collection"? Where do you retrieve nil?

2023-04-04 05:12 UTC, BugFreeSoftware requested changes

2023-04-04 05:12 UTC, BugFreeSoftware commented on packages/vm/core/accounts/impl_views.go
> +	collectionID := codec.MustDecodeNFTID(ctx.Params().Get(ParamCollectionID))
Try to cache values from the sandbox. ctx.Params() is a prime candicate for that. It is faster and it reduces gas fees.
Also, the Params has the kvdecoder built in, so no need for codec.MustDecodexxx. You can simply do params.MustDecodexxx like you do in the previous line.

2023-04-04 05:12 UTC, BugFreeSoftware commented on packages/wasmvm/wasmlib/go/wasmlib/wasmtypes/scagentid.go
> +		a.address = AddressFromBytes(append([]byte{ScAddressEth}, buf...))
AddressFromBytes will already correctly make an ETH ScAddress with type byte.
You may want to pull the latest develop or wasmclient into your PR. 
The scagentid.go as is is correct and passes all tests.

2023-04-04 19:48 UTC, howjmay commented on packages/vm/core/accounts/impl_views.go
> +		ParamNFTAmount: codec.EncodeUint32(cnt),
Thanks @dessaya for informing. The tests passed now. I reverted the change here

2023-04-04 19:50 UTC, howjmay commented on packages/vm/core/accounts/impl_views.go
> +	collectionID := codec.MustDecodeNFTID(ctx.Params().Get(ParamCollectionID))
Such a func doesn't exist in `KVDecoder` interface. Let me add it in this PR

2023-04-05 01:18 UTC, closed without merging