refactor: Remove duplicated WithAllowance
iotaledger/wasp-legacy pull request #2681
Opened 2023-07-06 07:35 UTC by howjmay

The behavior of `WithAllowance` and `AddAllowance` are duplicated.

2023-07-07 13:57 UTC, howjmay commented on packages/solo/req.go
> +func (ch *Chain) EstimateGasOffLedger(_req *CallParams, keyPair *cryptolib.KeyPair, useMaxBalance ...bool) (gas, gasFee uint64, err error) {
I think the argument `_req` shouldn't be change after executing the function.

2023-07-11 11:54 UTC, jorgemmsilva requested changes
I don't understand the motivation for this PR

`AddAllowance` and `WithAllowance` do different things, right? (`add` adds and `with` sets/overrides the current allowance)

2023-07-11 14:48 UTC, jorgemmsilva commented
closing for now, we can re-open if needed

2023-07-11 14:48 UTC, closed without merging

2023-07-11 16:36 UTC, howjmay commented on packages/solo/req.go
> +func (ch *Chain) EstimateGasOffLedger(_req *CallParams, keyPair *cryptolib.KeyPair, useMaxBalance ...bool) (gas, gasFee uint64, err error) {
@jorgemmsilva Do you think the change for this function is reasonable?