refactor: Use echo-jwt package
iotaledger/wasp-legacy pull request #2724
Opened 2023-07-16 11:27 UTC by howjmay

2023-07-18 17:32 UTC, lmoe commented
LGTM

There is a difference between the old and the new JWT payload:

old: `"aud": "wasp0"`
new: `"aud": [ "wasp0" ]`

Not sure important that is. It seems to work fine on the CLI.

2023-07-18 17:32 UTC, lmoe approved these changes

2023-07-18 17:34 UTC, lmoe requested changes
Sorry, I now tested a bit more.
It does not work with the CLI.

`chain list` seems to return an Unauthorized error result. I guess the JWT token is not read properly, not send properly, or is invalid.

2023-07-18 17:38 UTC, howjmay commented
> Sorry, I now tested a bit more. It does not work with the CLI.
> 
> `chain list` seems to return an Unauthorized error result. I guess the JWT token is not read properly, not send properly, is invalid or incorrectly validated on the backend.

Let me fix this

2023-07-19 14:36 UTC, jorgemmsilva commented on packages/authentication/jwt_auth.go
> +	const defaultJWTDuration = 24 * time.Hour
should be a config param

2023-07-20 16:18 UTC, jorgemmsilva approved these changes

2023-07-21 15:09 UTC, lmoe commented
Tests are successful now, LGTM!

2023-07-21 15:09 UTC, lmoe approved these changes

2023-07-21 20:47 UTC, merged