Improvement: handle excess outputs
iotaledger/wasp-legacy pull request #328
Opened 2021-08-10 12:02 UTC by jorgemmsilva

There is a limit of ouput a tx can have, if we exceed this limit the state transition tx won't be accepted by L1.

There is no way to know how many outputs a request will produce without executing it. Because of this, we can only cap the number of outputs produced during batch execution.

This PR adds the following behaviours for excess number of outputs produced:
 - if a single request produces more outputs than can fit in a tx, it fails with an error
 - if a request produces outputs that overflow the current limit (ex: 1 output too many), we rollback that request, stop batch processing and keep that request (and the others that weren't processed from the current batch) on the mempool to be picked-up again.

This PR also introduces:
 - limit of inputs that can fit in a tx ensured by the VM (this is already ensured in consensus, but its good to have a robust self-contained logic for the VM)
- a nonce of for outputs per request included in the request metadata (so we don't produce identical outputs, which results in an error)

depends on: https://github.com/iotaledger/goshimmer/pull/1614

2021-08-23 11:52 UTC, lunfardo314 requested changes

2021-08-23 11:52 UTC, lunfardo314 commented on packages/vm/vmcontext/general.go
> +		vmctx.log.Panicf("request with ID %s exceeded max number of allowed outputs (%d)", vmctx.req.ID().Base58(), MaxBlockOutputCount)
not good. It means some requests can panic for no reason for the caller and fee is still charged.
I think correct approach would be somehow signal the main loop in the VM not to include this request at all. It can be done for example with special panic code which could be intercepted and treated accordingly

2021-08-23 11:52 UTC, lunfardo314 commented on packages/vm/vmcontext/general.go
> +		vmctx.log.Panicf("request with ID %s exceeded max number of allowed outputs (%d)", vmctx.req.ID().Base58(), MaxBlockOutputCount)
oops, sorry, it seems it is exactly how it is implemented :)

2021-08-23 11:52 UTC, lunfardo314 commented on packages/vm/vmcontext/runreq.go
> +		vmctx.shouldStopRunningBatch = true
batch run should not be stopped, only no more on-ledger requests should be accepted (if inputs exceeded) and requests should be excluded if they want to create outputs but output count exceeded

2021-08-23 11:52 UTC, lunfardo314 commented on packages/vm/vmcontext/runreq.go
> +	if vmctx.shouldStopRunningBatch {
??

2021-08-23 11:52 UTC, lunfardo314 commented on packages/vm/vmcontext/vmcontext.go
> +var (
why not `const`?

2021-08-23 14:32 UTC, jorgemmsilva commented on packages/vm/vmcontext/vmcontext.go
> +var (
it was const initially, but I decided to use var in order to better test it:
https://github.com/jorgemmsilva/wasp/blob/impr/produced-outputs/packages/vm/core/testcore/output_limits_test.go#L73

2021-08-23 15:43 UTC, jorgemmsilva commented on packages/vm/vmcontext/runreq.go
> +		vmctx.shouldStopRunningBatch = true
makes sense, updated 👍

2021-08-23 15:43 UTC, jorgemmsilva commented on packages/vm/vmcontext/runreq.go
> +	if vmctx.shouldStopRunningBatch {
removed

2021-08-25 10:47 UTC, lunfardo314 approved these changes

2021-08-25 10:54 UTC, merged