* Minor edits on iscp.md
iotaledger/wasp-legacy pull request #330
Opened 2021-08-11 07:03 UTC by lucas-tortora

# Description of change

Minor text edit and formatting.  

## Links to any relevant issues

https://github.com/iotaledger/smartcontract-development/issues/27

## Type of change

- Documentation Enhancement

## How the change has been tested

It's just some minor text edits, but the site was built and run locally.

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the contribution guidelines for this project
- [ ] I have performed a self-review of my own code

2021-08-11 07:05 UTC, lucas-tortora commented
@iotaledger/tech-writers , could someone please review this before passing over to the WASP team?

2021-08-11 07:48 UTC, charlesthompson3 approved these changes
Again, super small edit. But good!

2021-08-11 07:48 UTC, charlesthompson3 commented on documentation/docs/guide/core_concepts/iscp.md
> +Allowing multiple blockchains to anchor to the tangle will solve several problems with smart contracts:
```suggestion
Allowing multiple blockchains to anchor to the tangle will solve several problems with smart contracts.
```

2021-08-11 10:04 UTC, jorgemmsilva commented on documentation/docs/guide/core_concepts/iscp.md
> +Due to the ordered structure and execution time of a smart contract, a single blockchain can only handle so many transactions per second before it needs to decide on which transactions need to be aba
>single blockchain can only handle so many transactions per second before it needs to decide on which transactions need to be abandoned, as there is no processing power available for them on that chain.

this feels misleading. tx usually just get postponed (need wait for one or many blocks to be produced) not "abandonen"

2021-08-11 11:35 UTC, lucas-tortora commented on documentation/docs/guide/core_concepts/iscp.md
> +Due to the ordered structure and execution time of a smart contract, a single blockchain can only handle so many transactions per second before it needs to decide on which transactions need to be aba
How about

2021-08-11 15:52 UTC, jorgemmsilva commented on documentation/docs/guide/core_concepts/iscp.md
> +Due to the ordered structure and execution time of a smart contract, a single blockchain can only handle so many transactions per second before it needs to decide on which transactions need to be aba
sounds good to me 👍

2021-08-13 23:40 UTC, aleksei-korolev requested changes

2021-08-13 23:40 UTC, aleksei-korolev commented on documentation/docs/guide/core_concepts/iscp.md
> +Wasp is the node software we have build to let you run smart contracts in a committee, using a virtual machine of choice. Multiple Wasp nodes connect and form a committee. If the validators in this c
```suggestion
Wasp is the node software that we have built to let you validate smart contracts as a part of a committee while using a virtual machine of your choice. Multiple Wasp nodes connect and form a committee of validators. When they reach consensus on a virtual machine state-change, they anchor that state change to the IOTA tangle, making it immutable. 
```

More precise words, more active voice.

2021-08-13 23:40 UTC, aleksei-korolev commented on documentation/docs/guide/core_concepts/iscp.md
> +ISCP stands for IOTA Smart Contract Protocol. It is IOTA's solution for running smart contracts on top of the IOTA tangle. With ISCP, we bring scalable and flexible smart contracts into the IOTA ecos
Good work on cutting the unnecessary. I personally would remove the comma for a better flow, even if the study book says otherwise.

I think we could state clearer that we allow any SCs anytime for anyone, as long as they support ISCP. This is not just about IOTA anymore, this is about making SCs free from specific blockchains and distributed networks. If I understand it right, the goal is to make it something like HTTP, used everywhere.

@iotaledger/smart-contracts prove me wrong.

```suggestion
ISCP stands for IOTA Smart Contract Protocol. It is IOTA's solution for running smart contracts on top of the IOTA tangle. With ISCP we bring scalable and flexible smart contracts into the IOTA ecosystem by allowing anyone to spin up a smart contract blockchain and anchor it to the IOTA tangle. 
```

2021-08-13 23:40 UTC, aleksei-korolev commented on documentation/docs/guide/core_concepts/iscp.md
>  ## What is ISCP?
We don't need this heading

2021-08-13 23:40 UTC, aleksei-korolev commented on documentation/docs/guide/core_concepts/iscp.md
> +Allowing multiple blockchains to anchor to the tangle will solve several problems with smart contracts.
Make a separate second-level section and add a TL;DR for the following subsections. Then this sentence wouldn't look so lonely.

2021-08-13 23:40 UTC, aleksei-korolev commented on documentation/docs/guide/core_concepts/iscp.md
> +Due to the ordered structure and execution time of a smart contract, a single blockchain can only handle so many transactions per second before it needs to decide on which transactions need to be pos
Active voice: ...before it has to decide which transactions it has to postpone or something like this

2021-08-13 23:40 UTC, aleksei-korolev commented on documentation/docs/guide/core_concepts/iscp.md
> +By allowing many chains to be anchored to the IOTA tangle, which in turn have the option to communicate with one another, we can simply add additional chains once this becomes a problem. This results
First sentence has too much in it and is rather tangled.

2021-08-13 23:40 UTC, aleksei-korolev commented on documentation/docs/guide/core_concepts/iscp.md
> +Given that anyone can start a new chain, and set the rules for that chain, a lot is possible. Not only do you have full control over how the fees are handled on the chain you set up, but you also hav
First sentence is weak and uncertain. In second sentence, the first half is tangled and has too much in it. Last sentence: instead of cold "this allows", use simple "parties that [...] can use [...].

"Can use" is motionless and too general, too. What do they do? Store? Anchor? Publish?

2021-08-13 23:40 UTC, aleksei-korolev commented on documentation/docs/guide/core_concepts/iscp.md
> +Every chain can be set up to run one, or multiple, virtual machines. We are starting with [Rust/WASM](https://rustwasm.github.io/docs/book/) based smart contracts, followed by [Solidity/EVM](https://
commas around "or multiple" kill the pace and you don't need them even by the book. Even better: just "multiple" instead of "one or multiple".

First sentence: active voice! "You can run multiple types of virtual machines on any chain " - 11 words against 13, and I added more information. The shortest version has 7, but lacks clarity: "Every chain could run multiple virtual machines".

Second sentence has no connection to the first one. You gotta rework it.

2021-08-13 23:40 UTC, aleksei-korolev commented on documentation/docs/guide/core_concepts/iscp.md
> +Compared to how a traditional smart contract implementation works, this particular architecture is a bit more complex, but it gives us a lot more freedom and flexibility to allow the usage of smart c
Cut it short: "ISCP is more complex than traditional smart contracts, but" or something like this.

Not so sure if smart contracts are old enough for some of them to become traditional. Conventional? Widespread? Common? Other?

a lot more to allow the usage of for a lot more use-cases? You can rewrite this sentence to be strong and free.

2021-08-19 06:20 UTC, lucas-tortora commented on documentation/docs/guide/core_concepts/iscp.md
> +Every chain can be set up to run one, or multiple, virtual machines. We are starting with [Rust/WASM](https://rustwasm.github.io/docs/book/) based smart contracts, followed by [Solidity/EVM](https://
changed the first sentence.  The second actually explains the roadmap for VM support.

2021-08-30 08:18 UTC, jorgemmsilva approved these changes

2021-08-31 12:52 UTC, fijter approved these changes
lgtm

2021-08-31 12:52 UTC, merged