devx/add missing docstrings in magic contracts
iotaledger/wasp-legacy pull request #3457
Opened 2024-07-03 14:54 UTC by Ginowine

# Description of change

Some of the magic contract reference docs are missing information about using the functions. This PR adds Solidity docstrings to the functions of the following contracts:

- [ ]  ISC
- [ ]  ISCAccounts
- [ ]  ISCPrivileged
- [ ]  ISCSandbox
- [ ]  ISCTypes
- [ ]  ISCUtil

## Links to any relevant issues

`fixes issue #3422 

## Type of change

- Documentation Fix

## Change checklist

Tick the boxes that are relevant to your changes, and delete any items that are not.

- [ ] I have followed the [contribution guidelines](/CONTRIBUTING.md) for this project
- [ ] I have performed a self-review of my own code
- [ ] I have selected the `develop` branch as the target branch
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that new and existing unit tests pass locally with my changes

2024-07-04 16:38 UTC, lucas-tortora approved these changes

2024-07-04 18:13 UTC, salaheldinsoliman requested changes
@Ginowine LGTM! except for this small comment:
NatSpec tags are all optional. That is, if `@notice` explains what the function does, there is no need to add a `@dev`. only add it when there are extra details
Can you please give it another small iteration, where if a `@notice` suffices just remove `@dev`
Thanks

2024-07-04 20:09 UTC, Ginowine commented
> @Ginowine LGTM! except for this small comment: NatSpec tags are all optional. That is, if `@notice` explains what the function does, there is no need to add a `@dev`. only add it when there are extra details Can you please give it another small iteration, where if a `@notice` suffices just remove `@dev` Thanks

@salaheldinsoliman. Ok great, thanks. I'll go through it again.

2024-07-19 15:50 UTC, lucas-tortora commented
could you rename the PR to follow the [guidelines on confluence](https://iotafoundation.atlassian.net/wiki/spaces/IF/pages/2202402957/PR+Review+Guidelines)?

2024-07-22 22:19 UTC, Dr-Electron requested changes

2024-07-22 22:19 UTC, Dr-Electron commented on packages/vm/core/evm/iscmagic/ISCAccounts.sol
> +     * @dev This function retrieves the number of NFTs owned by a given account.
```suggestion
     * @dev This function retrieves the IDs of NFTs owned by a given account.
```
An array of IDs is returned

2024-07-22 22:19 UTC, Dr-Electron commented on packages/vm/core/evm/iscmagic/ISCAccounts.sol
> +     * @dev This function retrieves the NFTs owned by a given account.
```suggestion
     * @dev This function retrieves the number of NFTs owned by a given account.
```

2024-07-22 22:19 UTC, Dr-Electron commented on packages/vm/core/evm/iscmagic/ISCSandbox.sol
> +     * @dev Sends the specified assets from the caller's L2 account to the EVM core contract's account and includes the specified metadata and options.
I would rephrase this.
```suggestion
     * @dev Sends the specified assets from the caller's L2 account to a L1 address and includes the specified metadata and options. This can also be used to create on-ledger requests to the chain itself.
```

2024-07-22 22:19 UTC, Dr-Electron commented on packages/vm/core/evm/iscmagic/ISCSandbox.sol
> +     * @param contractHname The hash name of the contract.
I would just use hname, that is what we use in the docs
```suggestion
     * @param contractHname The hname of the contract.
```

2024-07-22 22:19 UTC, Dr-Electron commented on packages/vm/core/evm/iscmagic/ISCSandbox.sol
> +     * @param contractHname The hash name of the contract.
Same here
```suggestion
     * @param contractHname The hname of the contract.
```

2024-07-22 22:19 UTC, Dr-Electron commented on packages/vm/core/evm/iscmagic/ISCTypes.sol
> +     * @return The type of the L1 address.
I guess we could add a note here about address types mentioned in this section? Or just ad this link
https://wiki.iota.org/tips/tips/TIP-0018/#address-unlock-condition

2024-07-24 02:36 UTC, Ginowine commented on packages/vm/core/evm/iscmagic/ISCTypes.sol
> +     * @return The type of the L1 address.
Ok, thanks; I added a note and the link.

2024-07-24 14:33 UTC, jorgemmsilva approved these changes

2024-07-24 20:54 UTC, Dr-Electron approved these changes

2024-07-25 10:19 UTC, salaheldinsoliman approved these changes

2024-07-25 10:19 UTC, merged