DKG and UDP peering.
iotaledger/wasp-legacy pull request #59
Opened 2020-12-14 08:27 UTC by kape1395

- Rabin-based DKG implemented and integrated.
  - Peering interface extracted, UDP based implementation added.

2020-12-14 16:36 UTC, lunfardo314 requested changes

2020-12-14 16:36 UTC, lunfardo314 commented on client/dkshares.go
> +// Copyright 2020 IOTA Stiftung
I think recommended practice is to put licence statement before the `package` , see for example https://github.com/google/go-licenses/blob/master/licenses/classifier_test.go

2020-12-14 16:36 UTC, lunfardo314 commented on main.go
> +	suite := pairing.NewSuiteBn256() // TODO: [KP] Single suite should be used in all the places.
Is it really necessary to use the same copy of suite everywhere?

2020-12-14 16:36 UTC, lunfardo314 commented on packages/chain/chainimpl/chainobj.go
> +	dkshare, err := dksProvider.LoadDKShare(&chr.ChainID)
I see chainID is now used as a key for DKShare  in the registry. **This is not correct**. DKShare must be accessed with the address (hash of the public key, corresponding to the distributed secret). ChainID is an alias of Address just temporary, until next refactoring of Goshimmer, with color locks. Then ChainID will become alias of the Color and ChainID will become impossible to use as a key for DKShare.

2020-12-14 16:36 UTC, lunfardo314 commented on packages/chain/chainimpl/interface.go
> +// TODO: [KP] Maybe we can use a broadcast instead of this?
essentially it is a broadcast, it also can be done in parallel

2020-12-14 16:36 UTC, lunfardo314 commented on packages/coretypes/chainid.go
> +func (chid *ChainID) Equal(other *ChainID) bool {
why we need this? ChainID is an byte array, can be compared by ==

2020-12-14 16:36 UTC, lunfardo314 commented on packages/peering/group/group.go
> +func (g *groupImpl) Broadcast(msg *peering.PeerMessage, includingSelf bool) {
may be spawned go routines to send in parallel. If that makes sense at all

2020-12-14 16:36 UTC, lunfardo314 commented on packages/registry/dkshare.go
> +func (r *Impl) LoadDKShare(chainID *coretypes.ChainID) (*tcrypto.DKShare, error) {
already commented above: address must be a key for DKShare in the registry, not ChainID

2020-12-14 17:54 UTC, kape1395 commented on client/dkshares.go
> +// Copyright 2020 IOTA Stiftung
Updated.

2020-12-15 12:18 UTC, kape1395 commented on main.go
> +	suite := pairing.NewSuiteBn256() // TODO: [KP] Single suite should be used in all the places.
I think it will be easier to ensure uniformity of the suite in use.

2020-12-15 13:52 UTC, kape1395 commented on packages/chain/chainimpl/chainobj.go
> +	dkshare, err := dksProvider.LoadDKShare(&chr.ChainID)
Fixed. Removed ChaniID from DKShare and related places.

2020-12-15 13:53 UTC, kape1395 commented on packages/chain/chainimpl/interface.go
> +// TODO: [KP] Maybe we can use a broadcast instead of this?
I think there is no need to make that in parallel now, because the sending part is not a bootleeneck.

2020-12-15 13:56 UTC, kape1395 commented on packages/coretypes/chainid.go
> +func (chid *ChainID) Equal(other *ChainID) bool {
It is unclear from the calling code, if the == comparison works for this kind of objects.
That's why I added this function.

2020-12-15 13:56 UTC, kape1395 commented on packages/peering/group/group.go
> +func (g *groupImpl) Broadcast(msg *peering.PeerMessage, includingSelf bool) {
That is not needed for now.

2020-12-15 13:57 UTC, kape1395 commented on packages/registry/dkshare.go
> +func (r *Impl) LoadDKShare(chainID *coretypes.ChainID) (*tcrypto.DKShare, error) {
Fixed.

2020-12-15 18:30 UTC, lunfardo314 approved these changes

2020-12-15 18:53 UTC, merged