added link to the Whitepaper on iota.org
iotaledger/wasp-legacy pull request #633
Opened 2021-11-26 10:01 UTC by Phyloiota

2021-11-28 00:26 UTC, grueegg requested changes

2021-11-28 00:26 UTC, grueegg commented on documentation/docs/guide/core_concepts/iscp-architecture.md
> +The multi-chain nature of IOTA Smart COntracts makes it a more complex implementation of smart contracts, over say Ethereum, as illustrated here:
Typo in Contracts --> O should be lower case

2021-12-07 05:23 UTC, charlesthompson3 commented
Refers to points 3 and 7 in https://github.com/iotaledger/docs.iota.org/issues/58

2021-12-07 22:49 UTC, Phyloiota reviewed
corrected the typo, thanks

2021-12-10 13:32 UTC, fijter approved these changes
Thanks! :)

2021-12-10 13:40 UTC, merged