refactor: vmrunner.Run() now returns results & receipts
iotaledger/wasp-legacy pull request #732
Opened 2022-01-12 17:54 UTC by dessaya

2022-01-13 07:33 UTC, lunfardo314 requested changes

2022-01-13 07:33 UTC, lunfardo314 commented on packages/vm/vmtask.go
> -	OnFinish                 func(callResult dict.Dict, callError error, vmError error)
why deleted `OnFinish` callback provided by the caller? For Solo it may not be very useful but it is very important for consensus, like here:  https://github.com/iotaledger/wasp/blob/8cd6ecdef31d66c974fb8f9ff3892b10fc135d83/packages/chain/consensus/action.go#L237  We defnitely need it, we can have default `nil` and do not call

2022-01-13 07:44 UTC, lunfardo314 requested changes

2022-01-13 07:44 UTC, lunfardo314 commented on packages/vm/runvm/runtask.go
>  	// optimistic read panic catcher for the whole VM task
the consensus run the task in goroutine and receive all results asynchronously via calling calback and passing a message with the same `VMTask` to the consensus. All results (state and transaction) are contained in the `VMTask`. Not to complicate things, we better put `[]*vm.RequestResult` into the VMTask structure too, next to the state and transaction essence, not return as a result of the function call.

2022-01-14 07:13 UTC, lunfardo314 approved these changes

2022-01-14 07:13 UTC, lunfardo314 commented on packages/solo/req.go
> -		DisableAutoAdjustDustDeposit: ch.Env.disableAutoAdjustDustDeposit,
why this deleted?

2022-01-14 07:13 UTC, merged

2022-01-14 12:47 UTC, dessaya commented on packages/solo/req.go
> -		DisableAutoAdjustDustDeposit: ch.Env.disableAutoAdjustDustDeposit,
Sorry, it is a mistake. I'll bring it back in another PR