feat: NFTs
iotaledger/wasp-legacy pull request #856
Opened 2022-03-04 18:30 UTC by jorgemmsilva

Initial NFT implementation

2022-03-04 19:00 UTC, dessaya approved these changes

2022-03-04 19:00 UTC, dessaya commented on packages/iscp/sandbox_interface.go
> +	NFT *NFT
This looks out of place. I mean, a public member of the struct that is not meant to be filled. No one will read the documentation :rofl: .

Maybe make both `NFTID` and `NFT` private? And add a method `WithNFT(NFTID id)` that fills in the NFT data, and `GetNFT() *NFT` for querying.

Or maybe split this object in two? Like `RequestParameters` and `ResolvedRequestParameters`.

2022-03-04 19:00 UTC, dessaya commented on packages/transaction/nfttransaction.go
> +type MintNftTransactionParams struct {
Nit: `MintNFTTransactionParams`

2022-03-04 19:00 UTC, dessaya commented on packages/vm/core/accounts/internal.go
> +func NFTmapEqual(a, b map[iotago.NFTID]bool) bool {
Nit: `NFTMapEqual`

2022-03-04 19:13 UTC, jorgemmsilva commented on packages/iscp/sandbox_interface.go
> +	NFT *NFT
you're 100% right 😄 
I also felt that this wasn't right, and even experimented creating a `RequestParametersWithNFTData`, but I didn't like that either, so I left it as is just to make it work for now.
(btw, even if the user fills it, it won't have any bad consequenses, it just gets overwritten, but still it will cause confusion for sure lol)

the suggestion to add a private field and getter/setters seems like a nice idea, will do that 👍

2022-03-05 11:33 UTC, lunfardo314 requested changes

2022-03-05 11:33 UTC, lunfardo314 commented on packages/iscp/sandbox_interface.go
> +	NFT *NFT
I am not a fan of this design. To make a request, we just have to specify existing NFT output, attach tokens and parameters to it and specify in allowance if target is allowed to take NFT or not. I'd prefer to have a special call for that, like `SendAsNFT` with some additional parameters and same call data struct. Now it looks like chimera

2022-03-05 11:33 UTC, lunfardo314 commented on packages/vm/core/accounts/internal.go
> +func MoveBetweenAccounts(state kv.KVStore, fromAgentID, toAgentID *iscp.AgentID, transfer *iscp.Allowance) bool {
this semantically not correct. Allowance is used as not allowance. I want to avoid that.
The correct way would be have separate functions to move fungible tokens and NFT as separate functions:
- `MoveBetweenAccounts` should stay without  modifications, probably renamed to `MoveBeteenAccountFungibleTokens`
- NFT should be moved by `MoveBetweenAccountsNFTs` with parameter of list of NFTs

2022-03-07 10:45 UTC, jorgemmsilva commented on packages/iscp/sandbox_interface.go
> +	NFT *NFT
>To make a request, we just have to specify existing NFT output

why shouldn't the NFTID be enough? no need to "specify the output" IMO

>and specify in allowance if target is allowed to take NFT or not

I opted to leave it this way because it allows to specify many NFTs, instead of a single one.

> I'd prefer to have a special call for that, like SendAsNFT with some additional parameters and same call data struct. Now it looks like chimera

We can change it to have `Send` and `SendAsNFT`, but we should discuss it - its more confusing imo to have 2 Send functions. What is the problem with the following? (I don't se a "chimera" :rofl: )

```golang
		ctx.Send(iscp.RequestParameters{
			...
			NFTID:                      nftID,
		})
	}
```

2022-03-07 10:51 UTC, jorgemmsilva commented on packages/vm/core/accounts/internal.go
> +func MoveBetweenAccounts(state kv.KVStore, fromAgentID, toAgentID *iscp.AgentID, transfer *iscp.Allowance) bool {
>this semantically not correct. Allowance is used as not allowance.

I don't understand this statement. What do you mean by this?

also what is the advantage of having `MoveBeteenAccountFungibleTokens` and `MoveBetweenAccountsNFTs`? :confused:

2022-03-07 12:14 UTC, jorgemmsilva commented
closed in favor of https://github.com/iotaledger/wasp/pull/859

2022-03-07 12:14 UTC, closed without merging