Stardust VM,  ADKG
iotaledger/wasp-legacy pull request #946
Opened 2022-04-13 15:26 UTC by kape1395

Asynchronous DKG.

2022-08-24 09:56 UTC, dessaya approved these changes

2022-08-24 13:04 UTC, Wollac requested changes

2022-08-24 13:04 UTC, Wollac commented on packages/gpa/rbc/bracha/bracha.go
> +	if float64(len(r.echoRecv[h])) >= math.Ceil(float64(r.n+r.f)/2.0) {
```suggestion
	// Send the READY message, if Byzantine quorum ⌈(n+f+1)/2⌉ of received ECHO messages is reached.
	// As there are only n distinct peers, every two Byzantine quorums overlap in at least one correct peer.
	// |echoRecv| ≥ ⌈(n+f+1)/2⌉ ⟺ |echoRecv| > ⌊(n+f)/2⌋
	if len(r.echoRecv[h]) > (r.n+r.f)/2 {
```
I think there is a "+1" missing in the quorum size and also the float computations could potentially pose problems. I've explained my reasoning the the proposed changes.

2022-08-24 13:04 UTC, Wollac commented on packages/gpa/rbc/bracha/bracha.go
> +}
```suggestion
	msgs := r.broadcast(msgBrachaTypeInitial, inputVal)
	r.initialSent = true
	return msgs
}

func (r *rbc) broadcast(t msgBrachaType, v []byte) []gpa.Message {
	var msgs []gpa.Message
	for i := range r.peers {
		msgs = append(msgs, &msgBracha{
			t: t,
			r: r.peers[i],
			v: v,
		})
	}
	return msgs
}
```
The exact same loop is executed several times, so I'd suggest to create a helper function for this.

2022-08-24 13:04 UTC, Wollac commented on packages/gpa/rbc/bracha/bracha.go
> +	if count >= r.f+1 {
```suggestion
	// Send the READY message, when a READY message was received from at least one honest peer.
	// This amplification assures totality.
	if count > r.f {
```
Only slight beautification

2022-08-24 13:04 UTC, Wollac commented on packages/gpa/rbc/bracha/bracha.go
> +	if !r.echoSent {
What is the reasoning behind also sending an ECHO (if not done yet) together with the READY?
For correctness it is definitely not needed  and I don't think I have ever seen this version in the literature...
Is it supposed to improve performance? I would intuitively just say it leads to more unnecessary messages. I would thus remove the ECHO from here to be closer to the algorithm.

2022-08-24 13:04 UTC, Wollac commented on packages/gpa/rbc/bracha/bracha.go
> +	if r.echoSent {
It is crucial here to check that `msg` is coming from the broadcaster! Only they are allowed to issues an INITIAL message.

2022-08-24 13:04 UTC, Wollac commented on packages/gpa/rbc/bracha/bracha.go
> +	h := r.ensureValueStored(msg.v)
I see an amplification attack here:
- there are no limits on the size of `v`
- it could be huge and exceed to peer's memory (either directly or when hashed)
- or cause problems when the peer broadcasts this huge message to other peers
- too large messages could be introduced by a malicious party at any stage of the algorithm.

As a simple fix, I would suggest to add an additional (global) config parameter to the constructor and check _all_ incoming messages against this size. For the actual program we can then either use the max message size, or come up with a reasonable max (maybe like 1MB)

2022-08-24 13:04 UTC, Wollac commented on packages/gpa/rbc/bracha/bracha.go
> +func SendPredicateUpdate(rbc gpa.GPA, me gpa.NodeID, predicate func([]byte) bool) []gpa.Message {
This predicate updating seems to be rather error-prone. Is it even still used somewhere?
Otherwise, I would strongly suggest to just remove it complete (and maybe only keep a static global predicate function in the constructor)

2022-08-24 13:04 UTC, Wollac commented
Only reviewed Bracha for now

2022-08-25 07:27 UTC, kape1395 commented on packages/gpa/rbc/bracha/bracha.go
> +	if float64(len(r.echoRecv[h])) >= math.Ceil(float64(r.n+r.f)/2.0) {
Good catch. Was probably lost between f and t.

2022-08-25 07:31 UTC, kape1395 commented on packages/gpa/rbc/bracha/bracha.go
> +	if count >= r.f+1 {
I have no strong opinion here. I personally prefer the `count > r.f`, as you suggested. But in a lot of papers and implementations the quorums are expressed as `count >= r.f+1`. Let's keep the simpler version. The same will be in a lot of other places.

2022-08-25 07:53 UTC, kape1395 commented on packages/gpa/rbc/bracha/bracha.go
> +	if r.echoSent {
Indeed, will add
```
	if msg.s != r.broadcaster {
		return gpa.NoMessages()
	}
```

2022-08-25 08:20 UTC, kape1395 commented on packages/gpa/rbc/bracha/bracha.go
> +	if !r.echoSent {
I was trying to be close to the algorithm in the paper:
```
//      Broadcast(v)
//      step 0. (By process p)
//          Send (initial, v) to all the processes.
//      step 1. Wait until the receipt of,
//              one (initial, v) message
//              or (n+t)/2 (echo, v) messages
//              or (t+l) (ready, v) messages
//              for some v.
//          Send (echo, v) to all the processes.
//      step 2. Wait until the receipt of,
//              (n+t)/2 (echo, v) messages
//              or (t+1) (ready, v) messages
//              (including messages received in step 1)
//              for some v.
//          Send (ready, v) to all the processes.
//      step 3. Wait until the receipt of,
//              2t+1 (ready, v) messages
//              (including messages received in step 1 and step 2) for some v.
//          Accept v.
```
Here, e.g. if a process don't receive the `(initial, v)` message but gets $(n+t)/2$ `(echo, v)` messages it suddenly satisfies conditions for steps 2 and 3, thus has to send `echo` and `ready` messages. This function does that.

2022-08-25 09:10 UTC, Wollac commented on packages/gpa/rbc/bracha/bracha.go
> +	if !r.echoSent {
OK, fair enough. Seems like I've never really read the original paper :see_no_evil: 
Turns you don't need to do that though. See for example here for an excellent write-up and proof: https://dcl.epfl.ch/site/_media/education/sdc_byzconsensus.pdf
I am mean the current version is obviously also fine. What would you intuitively say? You think the version without the ECHO could be preferable as it involves less messages?

2022-08-25 10:38 UTC, kape1395 commented on packages/gpa/rbc/bracha/bracha.go
> +	if !r.echoSent {
Intuitively -- I agree, it should be enough to send the READY messages.

Not sure, if that's true under partial/asymmetric partitions. Or we don't consider them. I guess a mis-configuration in the peering can easily cause those.

2022-08-25 10:55 UTC, kape1395 commented on packages/gpa/rbc/bracha/bracha.go
> +func SendPredicateUpdate(rbc gpa.GPA, me gpa.NodeID, predicate func([]byte) bool) []gpa.Message {
I simplified the predicate handling just now, only a single message can be postponed, to I made that explicit.
It is used in `packages/gpa/adkg/das`, but the latter is not used. Nevertheless, I would like to keep this function.
Update of the predicate is well defined, while the predicate sequence is monotonic IMO (i.e. if a message was accepted by a predicate, it has to be accepted by the following predicates as well).

2022-08-25 13:21 UTC, kape1395 commented on packages/gpa/rbc/bracha/bracha.go
> +func SendPredicateUpdate(rbc gpa.GPA, me gpa.NodeID, predicate func([]byte) bool) []gpa.Message {
Added  a TLA spec for this [BrachaRBC.tla](https://github.com/iotaledger/wasp/blob/stardust-vm-adkg/packages/gpa/rbc/bracha/BrachaRBC.tla).

2022-08-25 14:19 UTC, kape1395 commented on packages/gpa/rbc/bracha/bracha.go
> +	if !r.echoSent {
Aligned the implementation (and the TLA spec) with the algorithm presentation in Das et al.
The ECHO messages are not sent upon receiving READY anymore.

2022-08-26 09:15 UTC, kape1395 commented on packages/gpa/rbc/bracha/bracha.go
> +	h := r.ensureValueStored(msg.v)
Agree. Despite its hard to estimate the limit, it should be used here. Will add.

Also, the current code can store multiple values sent by a a single peer.
A correct node only send a message of particular type once, thus we should probably check, if a message of that was already received from the peer before storing the value. I will ignore the remaining messages, they can be caused by message re-delivery, not just a byzantine node.
This invariant holds, according to my spec:
```
SingleValueFromPeerPerMsgType ==
    \A m1, m2 \in msgs : (
        /\ m1.src \in CN
        /\ m1.src = m2.src
        /\ m1.t = m2.t
    ) => m1.v = m2.v
```

2022-08-26 09:36 UTC, Wollac commented on packages/gpa/rbc/bracha/bracha.go
> +	h := r.ensureValueStored(msg.v)
That is indeed a very good point!
Every (honest) peer sends each message type at most once. There should be a check for that very early in the handling and just reject any duplicates!

2022-08-26 10:49 UTC, Wollac requested changes

2022-08-26 10:49 UTC, Wollac commented on packages/gpa/rbc/bracha/bracha.go
> +	if len(r.echoRecv[h]) > 2*r.f {
```suggestion
	// |echoRecv| ≥ ⌈(n+f+1)/2⌉ ⟺ |echoRecv| > ⌊(n+f)/2⌋
	if len(r.echoRecv[h]) > (r.n+r.f)/2 {
```
$|E| > 2f$ is _only_ equivalent to the Byzantine quorum, if $n=3f+1$. If we happen to know that the number of faulty peers is lower than that, it is no longer correct.
Maybe you have strong assumptions and checks in WASP that $n=3f+1$ is indeed correct, but I would still strongly suggest to use the formula for the proper Byzantine quorum to be closer to the actual algorithm and be safe in all eventualities. 
Also, maybe it is just be but I don't find these different representations with $n$ and $f$ not trivial and hard to understand. That's why I proposed to add an explanation again why `⌊(n+f)/2⌋` is indeed equivalent. But feel free to ignore this additional comment if it is just me :sweat_smile:

2022-08-26 10:49 UTC, Wollac commented on packages/gpa/rbc/bracha/bracha.go
> +func SendPredicateUpdate(rbc gpa.GPA, me gpa.NodeID, predicate func([]byte) bool) []gpa.Message {
OK got it now. That single message is already making it much better (although I think it needs to be combined with the check from https://github.com/iotaledger/wasp/pull/946/files#r955842752)

Having a static predicate for the RBC is a very common trick, that you find in various algorithms and it makes definitely sense to integrate that. However, as I've said, usually it is assumed to be global and _static_.
As mentioned by you, Das et al. do it a bit differently by "switching" the RBC on when a certain condition is met.
In their paper they write "Participate in $j^{th}$ RBC when ...". They technically don't use the _Predicate_ for that. 
So an alternative implementation of Das Algorithms would be to cache all messages of the $j^{th}$ RBC in the DKG and only forward them to the RBC instance (without any predicate). Maybe this would even lead to a cleaner implementation as you automatically get the guarantee that you also know all the elements once the RBC finishes...

Anyways, I would suggest:

1. Remove the unused `packages/gpa/adkg/das` from this PR and into a separate branch.
2. Shortly consider whether we still need such a dynamic predicate. The monotonicity assumption is a bit unintuitive, but if you like to keep this functionality that is also fine. However, in that case we should make it a public method like `ChangePredicate`. Having it changed by a message is just dangerous and the wrong concept as no "outsider" must be allowed to change the predicate remotely.

2022-08-26 10:49 UTC, Wollac commented on packages/gpa/rbc/bracha/bracha.go
> +		return gpa.NoMessages()
Why not return `nil` instead. That would be the more Go idiomatic way and have exactly the same properties.

2022-08-26 11:17 UTC, kape1395 commented on packages/gpa/rbc/bracha/bracha.go
> +	h := r.ensureValueStored(msg.v)
- Added checks for duplicates `checkMsgRecv(...)`.
  - It appears we don't need to store the values in memory at all.
  - Added a limit on message size.

2022-08-26 12:24 UTC, Wollac commented on packages/gpa/rbc/bracha/bracha.go
> +	h := r.ensureValueStored(msg.v)
Yep, those changes look good!

2022-08-26 12:39 UTC, kape1395 commented on packages/gpa/rbc/bracha/bracha.go
> +		return gpa.NoMessages()
Good point. Will change that in other branch. I have started to reorganize things there a bit.

2022-08-29 09:19 UTC, jorgemmsilva commented on main.go
> +
this should be removed.
it is enough to turn on profiling via the config to enable pprof:
https://github.com/iotaledger/wasp/blob/develop/packages/parameters/parameters.go#L112-L113

2022-08-30 05:20 UTC, kape1395 commented on main.go
> +
Maybe that could be made a plugin, that is disabled by default?

2022-08-30 07:30 UTC, jorgemmsilva commented on main.go
> +
Yup, that is the case already 😄

2022-08-30 07:52 UTC, kape1395 commented on main.go
> +
@lmoe , maybe we can remove this part already?

2022-08-30 07:57 UTC, lmoe commented on main.go
> +
Yea I just didn't know that we have that already and I wanted to fix the bugs quickly. :D 
Of course we can remove that there.

2022-08-30 08:36 UTC, kape1395 commented on packages/gpa/rbc/bracha/bracha.go
> +func SendPredicateUpdate(rbc gpa.GPA, me gpa.NodeID, predicate func([]byte) bool) []gpa.Message {
OK, I'll remove that predicate update along with the adkg/das.
The ChangePredicate cannot be sent form outside, because it has no implementation for serialization.

2022-08-30 16:00 UTC, kape1395 commented on main.go
> +
OK, I removed it.

2022-08-31 11:15 UTC, Wollac reviewed
Bracha looks good to me now!
How do we wanna proceed? Merge everything for now and continue review in a different branch or continue in this PR?

2022-08-31 11:31 UTC, kape1395 commented
@Wollac , I continue improving stuff on the `gpa` branch (https://github.com/iotaledger/wasp/pull/1259) . Maybe you can proceed with a review there, or we can create a separate branch for it..

2022-08-31 11:36 UTC, Wollac approved these changes
A more thorough review will happen in a different branch

2022-09-02 11:15 UTC, merged